"use client";
import {notify} from "../../../../lib/notify";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Save } from "lucide-react";
import { supabase } from "../../../../lib/supabase";
import { saveServiceImage } from "../../../../lib/service-image";
import ModuleShell from "../../_components/ModuleShell";
import ImageCropper from "../../../_components/ImageCropper";
export default function NewService(){const router=useRouter(),[busy,setBusy]=useState(""),[error,setError]=useState(""),[crop,setCrop]=useState(null),[photo,setPhoto]=useState(null),[preview,setPreview]=useState("");return <ModuleShell title="Novo serviço" eyebrow="Catálogo">{({tenant})=><form className="box form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy("save");setError("");const f=new FormData(e.currentTarget),file=photo,ai=f.get("ai_photo")==="on",p={name:f.get("name"),description:f.get("description"),duration:Number(f.get("duration")),price_cents:Math.round(Number(f.get("price"))*100),commission_bps:Math.round(Number(f.get("commission"))*100),active:true};const {data:id,error}=await supabase.rpc("save_record",{t:tenant.id,k:"service",p});if(error){setBusy("");return setError(error.message)}
 // A foto vem depois do serviço criado: a enviada pelo usuário ou, se pedido, uma criada pela IA.
 let photoError="";if(file||ai){setBusy(file?"upload":"generate");try{await saveServiceImage(tenant.id,id,file?"upload":"generate",file)}catch(err){photoError=err.message}}
 setBusy("");notify(photoError?`Serviço criado, mas a foto não foi salva: ${photoError}`:"Serviço criado com sucesso.",photoError?"error":"success");router.push("/dashboard/servicos")}}><div className="form-grid"><label>Nome<input name="name" required placeholder="Ex.: Consulta inicial"/></label><label>Preço (R$)<input name="price" type="number" min="0" step="0.01" required placeholder="45,00"/></label><label>Duração (minutos)<input name="duration" type="number" min="5" max="480" required defaultValue="40"/></label><label>Comissão (%)<input name="commission" type="number" min="0" max="100" defaultValue="0"/></label></div><label>Descrição<textarea name="description" placeholder="Descrição exibida no agendamento"/></label><div className="form-field"><span className="form-label">Foto do serviço (opcional)</span><div className="new-service-photo">{preview?<img src={preview} alt="Prévia da foto"/>:<span>Sem foto</span>}<label className="secondary-action">{photo?"Trocar foto":"Escolher foto"}<input type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)setCrop(f)}}/></label>{photo&&<button type="button" className="secondary-action" onClick={()=>{setPhoto(null);setPreview("")}}>Remover</button>}</div></div>{crop&&<ImageCropper file={crop} shape="rounded" output={1000} title="Ajustar foto do serviço" onCancel={()=>setCrop(null)} onDone={f=>{setPhoto(f);setPreview(URL.createObjectURL(f));setCrop(null)}}/>}<label className="inventory-check"><input name="ai_photo" type="checkbox" defaultChecked/> Sem foto? Criar uma com IA pelo nome do serviço</label>{error&&<div className="form-alert error">{error}</div>}<button className="primary form-submit" disabled={!!busy}><Save size={17}/>{busy==="generate"?"Criando a foto com IA...":busy==="upload"?"Enviando a foto...":busy?"Salvando...":"Salvar serviço"}</button></form>}</ModuleShell>}
