"use client";
import "./admin-dark.css";
import {useEffect,useState} from "react";
import {Building2,CircleDollarSign,ExternalLink,FileText,KeyRound,LockKeyhole,LogOut,Plus,Scissors,ShieldCheck,Users} from "lucide-react";
import {useRouter} from "next/navigation";import {supabase} from "../../lib/supabase";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),date=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—";
export default function AdminPage(){
 const router=useRouter();const [loading,setLoading]=useState(true),[role,setRole]=useState(""),[plans,setPlans]=useState([]),[tenants,setTenants]=useState([]),[view,setView]=useState("register"),[error,setError]=useState(""),[report,setReport]=useState(null),[reportPass,setReportPass]=useState(""),[accesses,setAccesses]=useState([]),[accessLoading,setAccessLoading]=useState(false);
 const full=role==="full";
 async function reload(){await supabase.rpc("sync_tenant_billing_status",{p_tenant:null});const [p,t]=await Promise.all([supabase.from("plans").select("*").order("monthly_cents"),supabase.from("tenants").select("*,plans(name,monthly_cents)").order("created_at",{ascending:false})]);setPlans(p.data||[]);setTenants(t.data||[])}
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const {data}=await supabase.from("platform_admins").select("access_role").eq("user_id",user.id).maybeSingle();setRole(data?.access_role||"");if(data){await reload();if(data.access_role==="operations")setView("tenants")}setLoading(false)})()},[router]);
 async function token(){return (await supabase.auth.getSession()).data.session?.access_token}
 async function saveTenant(e){e.preventDefault();setError("");const f=new FormData(e.currentTarget),payload=Object.fromEntries(f);payload.slug=String(payload.slug||payload.name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const res=await fetch("/api/admin/tenants",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+await token()},body:JSON.stringify(payload)}),j=await res.json();if(!res.ok)return setError(j.error);e.currentTarget.reset();await reload();setView("tenants")}
 async function savePlan(e){e.preventDefault();const f=new FormData(e.currentTarget),p={kind:"plan",name:f.get("name"),monthly_cents:Math.round(+f.get("monthly")*100),extra_unit_cents:Math.round(+f.get("extra")*100),max_barbers:+f.get("max_barbers"),max_units:+f.get("max_units"),default_grace_days:+f.get("grace")};const {error}=await supabase.rpc("admin_save",{p});if(error)return setError(error.message);e.currentTarget.reset();await reload()}
 async function updateTenant(t,patch){const {error}=await supabase.rpc("admin_save",{p:{kind:"tenant",id:t.id,...patch}});if(error)return setError(error.message);await reload()}
 async function paid(t){const {error}=await supabase.rpc("admin_mark_paid",{p_tenant:t.id});if(error)return setError(error.message);await reload()}
 async function loadReport(e){e.preventDefault();const {data,error}=await supabase.rpc("admin_report",{p_password:reportPass});if(error)return setError(error.message);setError("");setReport(data)}
 async function setReportPassword(){const old=prompt("Digite a senha atual dos relatórios:");if(!old)return;const p=prompt("Digite a nova senha (mínimo 6 caracteres):");if(!p)return;const confirm=prompt("Confirme a nova senha:");if(confirm!==p)return setError("A confirmação da nova senha não confere.");const {error}=await supabase.rpc("admin_change_reports_password",{p_old_password:old,p_new_password:p});setError(error?.message||"");if(!error)alert("Senha dos relatórios atualizada com sucesso.")}
 async function loadAccess(){setAccessLoading(true);const r=await fetch("/api/admin/access",{headers:{authorization:"Bearer "+await token()}}),j=await r.json();setAccessLoading(false);if(!r.ok)return setError(j.error);setAccesses(j.items||[])}
 async function resetPassword(a){const p=prompt("Nova senha temporária para "+a.name+" (mínimo 8 caracteres):");if(!p)return;const r=await fetch("/api/admin/access",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+await token()},body:JSON.stringify({user_id:a.user_id,password:p})}),j=await r.json();if(!r.ok)return setError(j.error);alert("Senha redefinida com sucesso.")}
 async function addOperator(e){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/admin/operators",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+await token()},body:JSON.stringify(Object.fromEntries(f))}),j=await r.json();if(!r.ok)return setError(j.error);e.currentTarget.reset();alert("Acesso de operações criado.")}
 if(loading)return <main className="center-state">Carregando painel mestre...</main>;if(!role)return <main className="center-state">Acesso restrito.</main>;
 const nav=full?[["register","Cadastrar barbearia",Plus],["tenants","Barbearias",Building2],["plans","Planos",CircleDollarSign],["access","Acessos",KeyRound],["reports","Relatórios",FileText],["team","Equipe Barber Flow",Users]]:[["tenants","Barbearias",Building2]];
 return <main className="admin-layout"><aside className="admin-sidebar"><div className="brand-wrap"><div className="brand-mark"><Scissors/></div><div><div className="brand">Barber Flow</div><span className="brand-subtitle">Painel mestre</span></div></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setError("");if(id==="access")loadAccess()}}><I/>{label}</button>)}</nav><button className="admin-logout" onClick={()=>supabase.auth.signOut().then(()=>router.push("/login"))}><LogOut/>Sair</button></aside><section className="admin-content"><header><div><p className="eyebrow">{full?"SUPER ADMIN":"OPERAÇÕES"}</p><h1>{nav.find(x=>x[0]===view)?.[1]}</h1><p>{full?"Gestão completa da plataforma.":"Acesso limitado a ativação, bloqueio e pagamentos."}</p></div><span className="admin-badge"><ShieldCheck/>{full?"Administrador mestre":"Operações"}</span></header>{error&&<div className="form-alert error">{error}</div>}
 {view==="register"&&<form className="admin-register-page" onSubmit={saveTenant}>
 <section className="box admin-register-head"><div><span className="eyebrow">NOVO CLIENTE</span><h2>Cadastrar barbearia</h2><p>Crie a empresa, o acesso do proprietário e a assinatura.</p></div></section>
 <section className="box admin-register-section"><div className="admin-section-title"><span>1</span><div><h2>Dados da barbearia</h2><p>Informações principais e endereço público de agendamento.</p></div></div><div className="form-grid"><label>Nome da barbearia<input name="name" required/></label><label>Telefone<input name="phone"/></label><label>URL do agendamento<input name="slug" placeholder="Gerada automaticamente pelo nome"/></label></div></section>
 <section className="box admin-register-section"><div className="admin-section-title"><span>2</span><div><h2>Proprietário</h2><p>Este será o acesso principal da barbearia.</p></div></div><div className="form-grid"><label>Nome completo<input name="owner_name" required/></label><label>CPF<input name="owner_document" inputMode="numeric" required/></label><label>E-mail / login<input name="owner_email" type="email" required/></label><label>Senha inicial<input name="password" type="password" minLength="8" required/></label></div></section>
 <section className="box admin-register-section"><div className="admin-section-title"><span>3</span><div><h2>Gerente <small>opcional</small></h2><p>Identificação do responsável pela operação, se houver.</p></div></div><div className="form-grid"><label>Nome do gerente<input name="manager_name"/></label><label>CPF do gerente<input name="manager_document" inputMode="numeric"/></label></div></section>
 <section className="box admin-register-section"><div className="admin-section-title"><span>4</span><div><h2>Assinatura</h2><p>Plano, primeiro vencimento e regra de carência.</p></div></div><div className="form-grid"><label>Plano<select name="plan_id" required><option value="">Selecione o plano</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.monthly_cents)}</option>)}</select></label><label>Primeiro vencimento<input name="billing_due_date" type="date" required/></label><label>Contrato<select name="commitment_mode" defaultValue="annual"><option value="annual">12 meses · valor normal</option><option value="flex">Sem fidelidade · +15% na mensalidade</option></select></label><label>Desconto promocional (%)<input name="discount_pct" type="number" min="0" max="100" step=".01" defaultValue="0" placeholder="Ex.: 20"/></label><label>Duração do desconto<select name="discount_months" defaultValue="0"><option value="0">Sem desconto</option>{Array.from({length:24},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} {n===1?"mês":"meses"}</option>)}</select></label><div className="form-hint"><strong>Contrato anual:</strong> permanência de 12 meses pelo valor normal do plano. <strong>Sem fidelidade:</strong> acréscimo de 15% na mensalidade e cancelamento a qualquer momento.</div></div></section>
 <div className="admin-register-submit"><button className="primary" type="submit"><Plus size={16}/>Cadastrar barbearia</button><small>Ao cadastrar, o site público e o login do proprietário são criados automaticamente.</small></div>
 </form>}
 {view==="tenants"&&<><section className="admin-stats"><article><Building2/><div><strong>{tenants.length}</strong><span>Clientes</span></div></article><article><Users/><div><strong>{tenants.filter(x=>x.status==="active").length}</strong><span>Ativos</span></div></article><article><LockKeyhole/><div><strong>{tenants.filter(x=>["blocked","suspended"].includes(x.status)).length}</strong><span>Bloqueados</span></div></article></section><section className="box"><div className="module-toolbar"><div><h2>Administrar barbearias</h2><p>Ativação, bloqueio, vencimento e pagamento</p></div></div><div className="data-list admin-tenant-list">{tenants.map(t=><article key={t.id}><span className="service-icon"><Building2/></span><div><strong>{t.name}</strong><small>{t.plans?.name||"Sem plano"} · venc. {date(t.billing_due_date)} · carência {t.grace_days||0} dias</small><a className="mini-link" href={"/agendar/"+t.slug} target="_blank"><ExternalLink size={12}/>Site</a></div><select value={t.status} onChange={e=>updateTenant(t,{status:e.target.value})}><option value="active">Ativa</option><option value="trial">Teste</option><option value="overdue">Atrasada</option><option value="blocked">Bloqueada</option><option value="suspended">Suspensa</option><option value="cancelled">Cancelada</option></select><input type="date" value={t.billing_due_date||""} onChange={e=>updateTenant(t,{billing_due_date:e.target.value})}/><button className="paid-action" onClick={()=>paid(t)}>✓ Pagou</button></article>)}</div></section></>}
 {view==="plans"&&<section className="box"><div className="module-toolbar"><div><h2>Valores dos planos</h2><p>O Barber Flow possui somente Starter, Pro e Premium. Aqui você altera apenas o valor mensal.</p></div></div><div className="data-list">{plans.filter(p=>["Starter","Pro","Premium"].includes(p.name)).map(p=><article key={p.id}><div><strong>{p.name}</strong><small>{p.max_barbers} profissionais · {p.max_units} unidades</small></div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc("admin_save",{p:{kind:"plan",id:p.id,name:p.name,monthly_cents:Math.round(Number(f.get("monthly"))*100),extra_unit_cents:p.extra_unit_cents,max_barbers:p.max_barbers,max_units:p.max_units,default_grace_days:p.default_grace_days||0}});if(error)return setError(error.message);await reload()}}><label>Mensalidade<input name="monthly" type="number" min="0" step=".01" defaultValue={(p.monthly_cents/100).toFixed(2)}/></label><button className="secondary-action">Salvar valor</button></form></article>)}</div></section>}
 {view==="access"&&<section className="box"><div className="module-toolbar"><div><h2>Logins de donos e funcionários</h2><p>Senhas atuais não são exibidas; você pode redefini-las.</p></div><button className="secondary-action" onClick={loadAccess}>Atualizar</button></div>{accessLoading?<p>Carregando...</p>:<div className="data-list">{accesses.map(a=><article key={a.tenant_id+a.user_id}><div><strong>{a.name} · {a.tenant}</strong><small>{a.role} · {a.username?"@"+a.username+" · ":""}{a.email||"sem e-mail"}</small></div><span className={"pill "+(a.active?"confirmed":"")}>{a.active?"ativo":"bloqueado"}</span><button className="secondary-action" onClick={()=>resetPassword(a)}><KeyRound size={14}/>Redefinir senha</button></article>)}</div>}</section>}
 {view==="reports"&&<div className="admin-report">{!report?<form className="box form report-lock" onSubmit={loadReport}><LockKeyhole/><h2>Relatórios protegidos</h2><p>Esta área exige uma senha adicional.</p><input type="password" value={reportPass} onChange={e=>setReportPass(e.target.value)} placeholder="Senha dos relatórios"/><button className="primary">Entrar</button></form>:<><section className="admin-stats"><article><CircleDollarSign/><div><strong>{money(report.summary.mrr_cents)}</strong><span>Faturamento mensal</span></div></article><article><Users/><div><strong>{report.summary.active}</strong><span>Ativos</span></div></article><article><LockKeyhole/><div><strong>{report.summary.blocked}</strong><span>Bloqueados</span></div></article><article><CircleDollarSign/><div><strong>{report.summary.overdue}</strong><span>Inadimplentes</span></div></article><article><ShieldCheck/><div><strong>{report.summary.grace}</strong><span>Em carência</span></div></article></section><section className="box"><div className="module-toolbar"><div><h2>Relatório financeiro</h2><p>{report.summary.tenants} clientes cadastrados</p></div><button className="secondary-action" onClick={()=>window.print()}><FileText size={14}/>Gerar PDF</button></div><div className="data-list">{report.tenants.map(t=><article key={t.id}><div><strong>{t.name}</strong><small>{t.plan||"Sem plano"} · venc. {date(t.due_date)} · carência {t.grace_days} dias</small></div><span className={"pill "+(t.status==="active"?"confirmed":"")}>{t.status}</span><strong>{money(t.monthly_cents)}</strong></article>)}</div></section></>}</div>}
 {view==="team"&&<form className="box form" onSubmit={addOperator}><h2>Criar funcionário de operações</h2><p className="form-hint">Este acesso poderá ativar, bloquear, alterar vencimento e confirmar pagamento. Não terá acesso a planos, cadastros, acessos ou relatórios.</p><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Senha inicial<input name="password" type="password" minLength="8" required/></label><button className="primary">Criar acesso limitado</button></form>}
 </section></main>}
