"use client";
import Link from "next/link";
import RuptixFx from "../../_components/RuptixFx";
import "../../ruptix-home.css";
import {ArrowRight,BarChart3,CalendarDays,Check,Globe2,Instagram,MessageCircle,Sparkles,ShieldCheck,Smartphone,Users,WalletCards,Zap} from "lucide-react";

const features=[
 ["Agenda inteligente","Horários, profissionais, serviços e disponibilidade em uma agenda só.",CalendarDays],
 ["Site de agendamento","Cada salão ou estúdio ganha uma página própria para as clientes agendarem sozinhas.",Globe2],
 ["Vendas e PIX","Caixa rápido, pagamentos, vendas em conta e histórico financeiro.",WalletCards],
 ["Clientes","Cadastro, histórico de atendimentos e valores em aberto de cada cliente.",Users],
 ["WhatsApp","Confirmações e lembretes automáticos para reduzir faltas.",MessageCircle],
 ["Instagram","Mostre seus trabalhos mais recentes direto na página de agendamento.",Instagram],
];
export default function ProductPage(){return <main className="ruptix-site rx rx-beauty">
 <RuptixFx/><div className="rx-aurora" aria-hidden="true"><i/><i/><i/><i/></div><div className="rx-grid" aria-hidden="true"/>
 <nav className="rp-nav"><Link href="/" className="rp-logo">RUPTIX<span>.</span></Link><div><a href="#produto">Produto</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><a href="https://beautytix.3ruptix.com/login" className="rp-login">Entrar no BeautyTix</a></nav>
 <section className="rp-hero" id="produto"><div className="rp-glow"/><div className="rp-hero-copy"><span className="rp-tag"><Zap size={14}/> TECNOLOGIA PARA A BELEZA</span><h1>Seu espaço de beleza.<br/><em>Mais organizado.</em></h1><p>Conheça o <strong>BeautyTix</strong>, a plataforma da Ruptix feita para salões, estúdios de unhas, sobrancelhas e clínicas de estética: agenda, clientes, equipe, vendas e presença digital em um só lugar.</p><div className="rp-actions"><a href="#planos" className="rp-primary">Conhecer o BeautyTix <ArrowRight/></a><a href="https://beautytix.3ruptix.com/login" className="rp-secondary">Já sou cliente</a></div><div className="rp-trust"><span><ShieldCheck/>Gestão centralizada</span><span><Smartphone/>Feito para celular</span><span><BarChart3/>Controle do negócio</span></div></div>
 <div className="rp-product"><div className="rp-window"><div className="rp-window-top"><i/><i/><i/><span>BEAUTYTIX</span></div><div className="rp-demo"><aside><b>BT</b><span>Visão geral</span><span>Agenda</span><span>Clientes</span><span>Vendas</span><span>Profissionais</span></aside><section><small>VISÃO GERAL</small><h3>Bom dia, Patrícia.</h3><div className="rp-demo-stats"><div><small>Agendamentos</small><b>24</b></div><div><small>Vendas</small><b>R$ 2.480</b></div><div><small>Clientes</small><b>186</b></div></div><div className="rp-demo-card"><span>Próximos agendamentos</span><p>09:30 · Escova modeladora</p><p>10:15 · Manicure e pedicure</p><p>11:00 · Design de sobrancelhas</p></div></section></div></div><div className="rp-floating"><Sparkles/><div><b>BeautyTix</b><span>by Ruptix</span></div></div></div></section>
 <section className="rp-strip"><span>AGENDA</span><i/> <span>VENDAS</span><i/> <span>CLIENTES</span><i/> <span>PIX</span><i/> <span>WHATSAPP</span><i/> <span>RELATÓRIOS</span></section>
 <section className="rp-section" id="recursos"><div className="rp-section-head"><span>UM SISTEMA. TODA A OPERAÇÃO.</span><h2>Menos improviso.<br/>Mais controle.</h2><p>O BeautyTix reúne o essencial da rotina do salão em uma experiência simples para a dona do espaço e toda a equipe.</p></div><div className="rp-features">{features.map(([t,p,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="rp-showcase"><div><span>PARA QUEM QUER CRESCER</span><h2>Da recepção ao financeiro.</h2><p>Tenha uma visão clara da rotina do seu espaço, organize a equipe e ofereça uma experiência moderna para as suas clientes.</p></div><div className="rp-checks">{["Agenda individual por profissional","Página exclusiva de agendamento","Caixa rápido e formas de pagamento","Conta da cliente e controle de pendências","Painel administrativo e gestão da equipe","Experiência responsiva no celular"].map(x=><p key={x}><Check/>{x}</p>)}</div></section>
 <section className="rp-section rp-plans" id="planos"><div className="rp-section-head center"><span>PLANOS BEAUTYTIX</span><h2>Um plano para cada fase.</h2><p>Pro e Premium. Valores e condições comerciais são apresentados de acordo com a necessidade da sua operação.</p></div><div className="rp-plan-grid">{[["Pro","Para operações em crescimento."],["Premium","Para quem quer escalar."]].map(([n,d],i)=><article className={i===0?"featured":""} key={n}>{i===0&&<b className="rp-popular">MAIS COMPLETO</b>}<small>BEAUTYTIX</small><h3>{n}</h3><p>{d}</p><ul><li><Check/>Gestão do salão</li><li><Check/>Agenda e clientes</li><li><Check/>Vendas e financeiro</li><li><Check/>Site de agendamento</li></ul><a href="mailto:rup@3ruptix.com?subject=BeautyTix">Solicitar proposta <ArrowRight/></a></article>)}</div><p className="rp-contract">Contrato anual pelo valor normal do plano. Opção sem fidelidade disponível com acréscimo de 15% na mensalidade.</p></section>
 <section className="rp-cta"><div><span>RUPTIX APRESENTA</span><h2>BeautyTix.</h2><p>Uma nova forma de cuidar do seu espaço de beleza.</p></div><a href="mailto:rup@3ruptix.com?subject=BeautyTix">Quero conhecer <ArrowRight/></a></section>
 <footer className="rp-footer"><div><b>RUPTIX<span>.</span></b><p>Tecnologia para transformar operações.</p></div><div><strong>BEAUTYTIX</strong><a href="https://beautytix.3ruptix.com/login">Acessar sistema</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><small>© 2026 Ruptix. Todos os direitos reservados.</small></footer>
 </main>}