"use client";
import Link from "next/link";
import {ArrowRight,BarChart3,CalendarDays,Check,Globe2,Instagram,MessageCircle,Scissors,ShieldCheck,Smartphone,Users,WalletCards,Zap} from "lucide-react";

const features=[
 ["Agenda inteligente","Horários, profissionais, serviços e disponibilidade em uma agenda centralizada.",CalendarDays],
 ["Site de agendamento","Cada barbearia ganha sua própria página pública para receber agendamentos.",Globe2],
 ["Vendas e PIX","Caixa rápido, pagamentos, vendas em conta e histórico financeiro.",WalletCards],
 ["Clientes","Cadastro, histórico e controle de valores em aberto por cliente.",Users],
 ["WhatsApp","Estrutura preparada para atendimento e agendamentos pelo WhatsApp.",MessageCircle],
 ["Instagram","Conecte a presença digital da barbearia ao ecossistema BarberTix.",Instagram],
];
const tilt=e=>{const el=e.currentTarget,r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.setProperty("--ry",`${(x-.5)*10}deg`);el.style.setProperty("--rx",`${(.5-y)*8}deg`);el.style.setProperty("--mx",`${x*100}%`);el.style.setProperty("--my",`${y*100}%`)};
const resetTilt=e=>{e.currentTarget.style.setProperty("--ry","0deg");e.currentTarget.style.setProperty("--rx","0deg")};
export default function HomePage(){return <main className="ruptix-site">
 <nav className="rp-nav"><Link href="/" className="rp-logo">RUPTIX<span>.</span></Link><div><a href="#produto">Produto</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><Link href="/login" className="rp-login">Entrar no BarberTix</Link></nav>
 <section className="rp-hero" id="produto"><div className="rp-glow"/><div className="rp-hero-copy"><span className="rp-tag"><Zap size={14}/> TECNOLOGIA PARA BARBEARIAS</span><h1>Seu negócio.<br/><em>Em outro nível.</em></h1><p>Conheça o <strong>BarberTix</strong>, a plataforma da Ruptix criada para centralizar agenda, clientes, equipe, vendas e presença digital da sua barbearia.</p><div className="rp-actions"><a href="#planos" className="rp-primary">Conhecer o BarberTix <ArrowRight/></a><Link href="/login" className="rp-secondary">Já sou cliente</Link></div><div className="rp-trust"><span><ShieldCheck/>Gestão centralizada</span><span><Smartphone/>Feito para celular</span><span><BarChart3/>Controle do negócio</span></div></div>
 <div className="rp-product"><div className="rp-window"><div className="rp-window-top"><i/><i/><i/><span>BARBERTIX</span></div><div className="rp-demo"><aside><b>BT</b><span>Visão geral</span><span>Agenda</span><span>Clientes</span><span>Vendas</span><span>Equipe</span></aside><section><small>VISÃO GERAL</small><h3>Bom dia.</h3><div className="rp-demo-stats"><div><small>Agendamentos</small><b>24</b></div><div><small>Vendas</small><b>R$ 2.480</b></div><div><small>Clientes</small><b>186</b></div></div><div className="rp-demo-card"><span>Próximos agendamentos</span><p>09:30 · Corte + Barba</p><p>10:15 · Degradê</p><p>11:00 · Corte Premium</p></div></section></div></div><div className="rp-floating"><Scissors/><div><b>BarberTix</b><span>by Ruptix</span></div></div></div></section>
 <section className="rp-strip"><span>AGENDA</span><i/> <span>VENDAS</span><i/> <span>CLIENTES</span><i/> <span>PIX</span><i/> <span>WHATSAPP</span><i/> <span>RELATÓRIOS</span></section>
 <section className="rp-section" id="recursos"><div className="rp-section-head"><span>UM SISTEMA. TODA A OPERAÇÃO.</span><h2>Menos improviso.<br/>Mais controle.</h2><p>O BarberTix reúne as ferramentas essenciais da operação em uma experiência simples para o proprietário e sua equipe.</p></div><div className="rp-features">{features.map(([t,p,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="rp-showcase"><div><span>PARA QUEM QUER CRESCER</span><h2>Da cadeira ao financeiro.</h2><p>Tenha uma visão mais clara da rotina da barbearia, organize a equipe e ofereça uma experiência moderna para seus clientes.</p></div><div className="rp-checks">{["Agenda individual por profissional","Página exclusiva de agendamento","Caixa rápido e formas de pagamento","Conta do cliente e controle de pendências","Painel administrativo e gestão da equipe","Experiência responsiva no celular"].map(x=><p key={x}><Check/>{x}</p>)}</div></section>
 <section className="rp-section rp-plans" id="planos"><div className="rp-section-head center"><span>PLANOS BARBERTIX</span><h2>Um plano para cada fase.</h2><p>Pro e Premium. Valores e condições comerciais são apresentados de acordo com a necessidade da sua operação.</p></div><div className="rp-plan-grid">{[["Pro","Para operações em crescimento."],["Premium","Para quem quer escalar."]].map(([n,d],i)=><article className={i===0?"featured":""} key={n} onMouseMove={tilt} onMouseLeave={resetTilt}>{i===0&&<b className="rp-popular">MAIS COMPLETO</b>}<small>BARBERTIX</small><h3>{n}</h3><p>{d}</p><ul><li><Check/>Gestão da barbearia</li><li><Check/>Agenda e clientes</li><li><Check/>Vendas e financeiro</li><li><Check/>Site de agendamento</li></ul><a href="mailto:contato@3ruptix.com">Solicitar proposta <ArrowRight/></a></article>)}</div><p className="rp-contract">Contrato anual pelo valor normal do plano. Opção sem fidelidade disponível com acréscimo de 15% na mensalidade.</p></section>
 <section className="rp-cta"><div><span>RUPTIX APRESENTA</span><h2>BarberTix.</h2><p>Uma nova forma de administrar sua barbearia.</p></div><a href="mailto:contato@3ruptix.com">Quero conhecer <ArrowRight/></a></section>
 <footer className="rp-footer"><div><b>RUPTIX<span>.</span></b><p>Tecnologia para transformar operações.</p></div><div><strong>BARBERTIX</strong><Link href="/login">Acessar sistema</Link><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><small>© 2026 Ruptix. Todos os direitos reservados.</small></footer>
 </main>}