"use client";
import {useEffect,useMemo,useState} from "react";
import {CircleDollarSign,Search,WalletCards} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import ModuleShell from "../_components/ModuleShell";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels={pix:"PIX",cash:"Dinheiro",credit:"Crédito",debit:"Débito",account:"Conta do cliente"};
function Sales({workspace}){const [items,setItems]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true);
useEffect(()=>{supabase.from("appointment_payments").select("id,amount_cents,method,status,paid_at,created_at,clients(name),barbers(name),services(name),units(name)").eq("tenant_id",workspace.tenant.id).order("created_at",{ascending:false}).limit(500).then(({data})=>{setItems(data||[]);setLoading(false)})},[workspace.tenant.id]);
const filtered=items.filter(x=>(x.clients?.name||"").toLowerCase().includes(q.toLowerCase())||(x.services?.name||"").toLowerCase().includes(q.toLowerCase())),paid=items.filter(x=>x.status==="paid"),today=new Date().toDateString(),todayTotal=paid.filter(x=>new Date(x.paid_at||x.created_at).toDateString()===today).reduce((s,x)=>s+x.amount_cents,0),total=paid.reduce((s,x)=>s+x.amount_cents,0),open=items.filter(x=>x.status==="open").reduce((s,x)=>s+x.amount_cents,0);
return <><div className="report-cards"><div className="metric-card"><small>Recebido hoje</small><strong>{money(todayTotal)}</strong></div><div className="metric-card"><small>Total recebido</small><strong>{money(total)}</strong></div><div className="metric-card"><small>Conta de clientes</small><strong>{money(open)}</strong></div><div className="metric-card"><small>Pagamentos</small><strong>{paid.length}</strong></div></div><section className="box"><div className="module-toolbar"><div><h2>Histórico de vendas</h2><p>Pagamentos dos atendimentos finalizados</p></div><label className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente ou serviço"/></label></div>{loading?<p className="empty">Carregando...</p>:filtered.length===0?<div className="empty-state"><WalletCards/><strong>Nenhuma venda registrada</strong></div>:<div className="data-list">{filtered.map(x=><article key={x.id}><span className="service-icon"><CircleDollarSign/></span><div><strong>{x.clients?.name||"Cliente"} · {x.services?.name||"Serviço"}</strong><small>{new Date(x.paid_at||x.created_at).toLocaleString("pt-BR")} · {x.barbers?.name||"Profissional"} · {labels[x.method]||x.method}</small></div><div className="sale-value"><strong>{money(x.amount_cents)}</strong><span className={"pill "+(x.status==="paid"?"confirmed":"")}>{x.status==="open"?"Em aberto":"Pago"}</span></div></article>)}</div>}</section></>}
export default function SalesPage(){return <ModuleShell title="Vendas" eyebrow="Financeiro">{workspace=><Sales workspace={workspace}/>}</ModuleShell>}