"use client";
import {useEffect,useState} from "react";
import {CircleDollarSign,Pencil,Search,Trash2,WalletCards,X} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import ModuleShell from "../_components/ModuleShell";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels={pix:"PIX",cash:"Dinheiro",credit:"Crédito",debit:"Débito",account:"Conta do cliente"};
function Sales({workspace}){const [items,setItems]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[editing,setEditing]=useState(null),[error,setError]=useState("");const owner=workspace.membership?.role==="owner";
async function load(){setLoading(true);const [a,qx]=await Promise.all([supabase.from("appointment_payments").select("id,amount_cents,method,status,paid_at,created_at,clients(name),barbers(name),services(name),units(name)").eq("tenant_id",workspace.tenant.id).order("created_at",{ascending:false}).limit(500),supabase.from("quick_sales").select("id,amount_cents,method,status,paid_at,created_at,description,clients(name),barbers(name)").eq("tenant_id",workspace.tenant.id).order("created_at",{ascending:false}).limit(500)]);const appointments=(a.data||[]).map(x=>({...x,type:"appointment",description:x.services?.name||"Atendimento"})),quick=(qx.data||[]).map(x=>({...x,type:"quick",services:{name:x.description},units:null}));setItems([...appointments,...quick].sort((x,y)=>new Date(y.created_at)-new Date(x.created_at)));setLoading(false)}
useEffect(()=>{load()},[workspace.tenant.id]);
async function save(e){e.preventDefault();const f=new FormData(e.currentTarget),{error}=await supabase.rpc("owner_manage_sale",{t:workspace.tenant.id,sale_id:editing.id,sale_type:editing.type,action:"update",new_method:f.get("method"),new_status:f.get("status")});if(error)return setError(error.message);setEditing(null);await load()}
async function remove(x){if(!confirm("Apagar esta venda do histórico? Esta ação não pode ser desfeita."))return;const {error}=await supabase.rpc("owner_manage_sale",{t:workspace.tenant.id,sale_id:x.id,sale_type:x.type,action:"delete",new_method:null,new_status:null});if(error)return setError(error.message);await load()}
const filtered=items.filter(x=>(x.clients?.name||"").toLowerCase().includes(q.toLowerCase())||(x.services?.name||"").toLowerCase().includes(q.toLowerCase())),paid=items.filter(x=>x.status==="paid"),today=new Date().toDateString(),todayTotal=paid.filter(x=>new Date(x.paid_at||x.created_at).toDateString()===today).reduce((s,x)=>s+x.amount_cents,0),total=paid.reduce((s,x)=>s+x.amount_cents,0),open=items.filter(x=>x.status==="open").reduce((s,x)=>s+x.amount_cents,0);
return <><div className="report-cards"><div className="metric-card"><small>Recebido hoje</small><strong>{money(todayTotal)}</strong></div><div className="metric-card"><small>Total recebido</small><strong>{money(total)}</strong></div><div className="metric-card"><small>Conta de clientes</small><strong>{money(open)}</strong></div><div className="metric-card"><small>Pagamentos</small><strong>{paid.length}</strong></div></div><section className="box"><div className="module-toolbar"><div><h2>Histórico de vendas</h2><p>Atendimentos e vendas do Caixa Rápido</p></div><label className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente ou serviço"/></label></div>{error&&<div className="form-alert error">{error}</div>}{loading?<p className="empty">Carregando...</p>:filtered.length===0?<div className="empty-state"><WalletCards/><strong>Nenhuma venda registrada</strong></div>:<div className="data-list">{filtered.map(x=><article key={x.type+x.id}><span className="service-icon"><CircleDollarSign/></span><div><strong>{x.clients?.name||"Cliente"} · {x.services?.name||"Serviço"}</strong><small>{new Date(x.paid_at||x.created_at).toLocaleString("pt-BR")} · {x.barbers?.name||"Profissional"} · {labels[x.method]||x.method}</small></div><div className="sale-value"><strong>{money(x.amount_cents)}</strong><span className={"pill "+(x.status==="paid"?"confirmed":"")}>{x.status==="open"?"Em aberto":x.status==="cancelled"?"Cancelado":"Pago"}</span>{owner&&<span className="sale-owner-actions"><button onClick={()=>setEditing(x)} title="Editar venda"><Pencil size={14}/></button><button onClick={()=>remove(x)} title="Apagar venda"><Trash2 size={14}/></button></span>}</div></article>)}</div>}</section>{editing&&owner&&<div className="checkout-backdrop"><form className="checkout-modal" onSubmit={save}><button type="button" className="checkout-close" onClick={()=>setEditing(null)}><X/></button><p className="eyebrow">CONTROLE DO PROPRIETÁRIO</p><h2>Editar venda</h2><p>{editing.clients?.name||"Cliente"} · {editing.services?.name}</p><strong className="checkout-total">{money(editing.amount_cents)}</strong><label>Forma de pagamento<select name="method" defaultValue={editing.method}><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="credit">Crédito</option><option value="debit">Débito</option><option value="account">Conta do cliente</option></select></label><label>Status<select name="status" defaultValue={editing.status}><option value="paid">Pago</option><option value="open">Em aberto</option><option value="cancelled">Cancelado</option></select></label><button className="primary checkout-confirm">Salvar alteração</button></form></div>}</>}
export default function SalesPage(){return <ModuleShell title="Vendas" eyebrow="Financeiro">{workspace=><Sales workspace={workspace}/>}</ModuleShell>}