"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight,Eye,EyeOff,Scissors } from "lucide-react";
import { supabase } from "../../lib/supabase";
export default function LoginPage(){
 const router=useRouter(); const [mode,setMode]=useState("login"); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{if(!supabase)return;const recovery=location.hash.includes("type=recovery")||new URLSearchParams(location.search).has("code");if(recovery)setMode("new-password");const {data}=supabase.auth.onAuthStateChange(event=>{if(event==="PASSWORD_RECOVERY")setMode("new-password")});return()=>data.subscription.unsubscribe()},[]);
 async function submit(event){event.preventDefault();setLoading(true);setError("");setMessage("");const form=new FormData(event.currentTarget),rawLogin=String(form.get("email")||"").trim(),password=form.get("password");let email=rawLogin;if(mode==="login"&&rawLogin.startsWith("@")){const username=rawLogin.slice(1).toLowerCase();const {data:matches}=await supabase.from("staff_logins").select("login_email").eq("username",username).limit(2);if(!matches||matches.length!==1){setLoading(false);setError("Usuário ou senha incorretos.");return}email=matches[0].login_email;}if(!supabase){setError("Conexão com o banco não configurada.");setLoading(false);return}
  if(mode==="reset"){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/login`});setLoading(false);return error?setError(error.message):setMessage("Enviamos o link de recuperação para seu e-mail.")}
  if(mode==="new-password"){const {error}=await supabase.auth.updateUser({password});setLoading(false);if(error)return setError(error.message);setMessage("Senha alterada com sucesso. Abrindo seu painel...");setTimeout(()=>{router.replace("/admin");router.refresh()},900);return}
  const result=mode==="signup"?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setLoading(false);if(result.error)return setError(result.error.message==="Invalid login credentials"?"E-mail ou senha incorretos.":result.error.message);if(mode==="signup"&&!result.data.session)return setMessage("Conta criada. Confirme o e-mail para entrar.");const userId=result.data.user?.id||result.data.session?.user?.id;const {data:admin}=userId?await supabase.from("platform_admins").select("user_id").eq("user_id",userId).maybeSingle():{data:null};router.push(admin?"/admin":"/dashboard");router.refresh();
 }
 return <main className="auth-page"><section className="auth-brand"><div className="auth-logo"><Scissors/> Barber Flow</div><div><span className="auth-kicker">GESTÃO QUE TRANSFORMA</span><h1>Mais controle.<br/>Mais clientes.<br/><em>Mais crescimento.</em></h1><p>Administre sua barbearia de qualquer lugar, com tudo o que você precisa em um só sistema.</p></div><small>© 2026 Barber Flow</small></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="mobile-auth-logo"><Scissors/> Barber Flow</div><span className="auth-welcome">BEM-VINDO</span><h2>{mode==="login"?"Acesse sua conta":mode==="signup"?"Crie sua conta":mode==="new-password"?"Crie uma nova senha":"Recupere sua senha"}</h2><p>{mode==="reset"?"Digite seu e-mail para receber o link.":mode==="new-password"?"Digite abaixo a nova senha da sua conta.":"Entre com seus dados para continuar."}</p>{mode!=="new-password"&&<label>{mode==="login"?"E-mail ou usuário":"E-mail"}<input name="email" type="text" autoComplete="username" placeholder={mode==="login"?"voce@email.com ou @anthony01":"voce@email.com"} required/></label>}{mode!=="reset"&&<label>{mode==="new-password"?"Nova senha":"Senha"}<div className="password-field"><input name="password" type={show?"text":"password"} minLength="6" autoComplete={mode==="login"?"current-password":"new-password"} placeholder={mode==="new-password"?"Escolha sua nova senha":"Sua senha"} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}{error&&<div className="form-alert error">{error}</div>}{message&&<div className="form-alert success">{message}</div>}<button className="auth-submit" disabled={loading}>{loading?"Aguarde...":mode==="login"?"Entrar":mode==="signup"?"Criar conta":mode==="new-password"?"Salvar nova senha":"Enviar link"}<ArrowRight size={18}/></button>{mode!=="new-password"&&<div className="auth-links">{mode==="login"&&<button type="button" onClick={()=>setMode("reset")}>Esqueci minha senha</button>}<button type="button" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Já tenho uma conta":"Criar uma conta"}</button></div>}</form></section></main>
}
