"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,Eye,EyeOff,Mail,LockKeyhole} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import styles from './login.module.css';
const titles={login:'Acesse sua conta',signup:'Crie sua conta grátis',reset:'Recupere sua senha','new-password':'Crie sua senha'};
export default function LoginPage(){
 const router=useRouter(),pending=useRef(false);
 const [mode,setMode]=useState('login'),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[caps,setCaps]=useState(false);
 useEffect(()=>{if(!supabase)return;let alive=true;const params=new URLSearchParams(location.search),hash=location.hash;const setup=params.get('setup')==='password'||hash.includes('type=invite')||hash.includes('type=recovery')||params.has('code');if(setup)setMode('new-password');else if(params.get('criar')==='1')setMode('signup');(async()=>{const {data:current,error}=await supabase.auth.getUser();if(alive&&!error&&current?.user&&hash.includes('type=signup')){location.replace('/onboarding');return}if(!alive||!error)return;const msg=String(error.message||"");if(/invalid refresh token|refresh token not found|jwt expired/i.test(msg)){try{await supabase.auth.signOut({scope:"local"})}catch{}try{Object.keys(localStorage).filter(k=>k.startsWith("sb-")&&k.endsWith("-auth-token")).forEach(k=>localStorage.removeItem(k))}catch{}}})();const {data}=supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'||(event==='SIGNED_IN'&&new URLSearchParams(location.search).get('setup')==='password'))setMode('new-password')});return()=>{alive=false;data.subscription.unsubscribe()}},[]);
 function changeMode(next){setMode(next);setShow(false);setCaps(false);setError('');setMessage('')}
 async function goToPanel(userId){const {data:admin}=userId?await supabase.from('platform_admins').select('user_id').eq('user_id',userId).maybeSingle():{data:null};router.replace(admin?'/admin':'/dashboard');router.refresh()}
 async function submit(event){
  event.preventDefault();if(pending.current)return;pending.current=true;setLoading(true);setError('');setMessage('');
  const form=new FormData(event.currentTarget);let email=String(form.get('email')||'').trim();const password=String(form.get('password')||'');
  try{
   if(!supabase)throw new Error('Conexão indisponível. Tente novamente em instantes.');
   if(mode==='login'&&(email.startsWith('@')||!email.includes('@'))){const {data:loginEmail,error:lookupError}=await supabase.rpc('staff_login_email',{p_username:email});if(lookupError||!loginEmail)throw new Error('E-mail, usuário ou senha incorretos.');email=loginEmail}
   if(mode==='signup'){const {data,error:signUpError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/onboarding'}});if(signUpError)throw signUpError;if(data.session){router.replace('/onboarding');router.refresh();return}/* Com confirmação de e-mail ligada, um e-mail já cadastrado volta sem identidades. */if(Array.isArray(data.user?.identities)&&data.user.identities.length===0)throw new Error('Este e-mail já tem uma conta. Toque em "Já tenho conta" para entrar.');setMessage('Enviamos um link de confirmação para '+email+'. Abra o link para cadastrar sua empresa e começar os 14 dias grátis. Confira também o spam.');return}
   if(mode==='reset'){const {error:resetError}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/login'});if(resetError)throw resetError;setMessage('Se este e-mail estiver cadastrado, você receberá um link para recuperar a senha. Confira também o spam.');return}
   if(mode==='new-password'){const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;setMessage('Senha alterada. Abrindo seu painel...');const {data:{user}}=await supabase.auth.getUser();await goToPanel(user?.id);return}
   const result=await supabase.auth.signInWithPassword({email,password});
   if(result.error)throw result.error;
   await goToPanel(result.data.user?.id||result.data.session?.user?.id);
  }catch(e){const text=e?.message||'';setError(text==='Invalid login credentials'?'E-mail, usuário ou senha incorretos.':/already registered/i.test(text)?'Este e-mail já tem uma conta. Toque em "Já tenho conta" para entrar.':/signups not allowed/i.test(text)?'O cadastro está fechado no momento. Fale com rup@3ruptix.com.':/password should be at least/i.test(text)?'A senha precisa ter pelo menos 6 caracteres.':text==='Email not confirmed'?'Confirme seu e-mail antes de entrar.':/fetch|network/i.test(text)?'Não foi possível conectar. Confira sua internet e tente novamente.':text||'Não foi possível concluir. Tente novamente.')}finally{pending.current=false;setLoading(false)}
 }
 return <main className={styles.page}>
  <section className={styles.brand}><div className={styles.logo}><span className={styles.mark} aria-hidden="true"/>RupControl</div><div><span className={styles.kicker}>GESTÃO QUE TRANSFORMA</span><h1>Mais controle.<br/>Mais clientes.<br/><em>Mais crescimento.</em></h1><p>Administre seu negócio de qualquer lugar, com tudo o que você precisa em um só sistema.</p></div><small>RupControl · by Ruptix</small></section>
  <section className={styles.panel} aria-label="Acesso ao RupControl"><form className={styles.card} onSubmit={submit} aria-busy={loading}>
   <div className={styles.mobileLogo+' '+styles.logo}><span className={styles.mark} aria-hidden="true"/>RupControl</div><span className={styles.welcome}>{mode==='login'?'BEM-VINDO DE VOLTA':mode==='signup'?'14 DIAS GRÁTIS':'SUA CONTA'}</span><h2>{titles[mode]}</h2><p className={styles.intro}>{mode==='reset'?'Informe seu e-mail para receber o link de recuperação.':mode==='new-password'?'Seu convite foi confirmado. Agora escolha sua senha de acesso com pelo menos 6 caracteres.':mode==='signup'?'Crie seu acesso e cadastre sua empresa para usar o RupControl grátis por 14 dias. Sem cartão de crédito: o pagamento só começa depois do teste.':'Seu negócio organizado começa aqui.'}</p>
   {mode!=='new-password'&&<div className={styles.field}><label className={styles.label} htmlFor="login-email">{mode==='login'?'E-mail ou usuário':'E-mail'}</label><div className={styles.inputWrap}><Mail className={styles.inputIcon} aria-hidden="true"/><input id="login-email" className={styles.input} name="email" type={mode==='login'?'text':'email'} autoComplete={mode==='login'?'username':'email'} autoCapitalize="none" autoCorrect="off" spellCheck={false} inputMode={mode==='login'?'text':'email'} placeholder={mode==='login'?'Seu e-mail ou @usuário':'voce@email.com'} required disabled={loading}/></div></div>}
   {mode!=='reset'&&<div className={styles.field}><label className={styles.label} htmlFor="login-password">{mode==='new-password'?'Nova senha':'Senha'}</label><div className={styles.inputWrap}><LockKeyhole className={styles.inputIcon} aria-hidden="true"/><input id="login-password" className={styles.input+' '+styles.password} name="password" type={show?'text':'password'} minLength={mode==='login'?undefined:6} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='login'?'Digite sua senha':'No mínimo 6 caracteres'} onKeyUp={e=>setCaps(e.getModifierState('CapsLock'))} onBlur={()=>setCaps(false)} aria-describedby={caps?'caps-warning':undefined} required disabled={loading}/><button className={styles.toggle} type="button" disabled={loading} aria-label={show?'Ocultar senha':'Mostrar senha'} aria-pressed={show} aria-controls="login-password" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{caps&&<p id="caps-warning" className={styles.caps}>Caps Lock ativado</p>}</div>}
   {error&&<div className={styles.alert} role="alert">{error}</div>}{message&&<div className={styles.alert+' '+styles.success} role="status">{message}</div>}
   <button className={styles.submit} type="submit" disabled={loading}>{loading?'Aguarde...':mode==='login'?'Entrar':mode==='signup'?'Criar conta grátis':mode==='new-password'?'Criar minha senha':'Enviar link'}<ArrowRight size={18} aria-hidden="true"/></button>
   {mode!=='new-password'&&<div className={styles.links}>{mode==='login'?<><button className={styles.link} disabled={loading} type="button" onClick={()=>changeMode('reset')}>Esqueci minha senha</button><button className={styles.link+' '+styles.signupLink} disabled={loading} type="button" onClick={()=>changeMode('signup')}>Criar conta · 14 dias grátis</button></>:<button className={styles.link} disabled={loading} type="button" onClick={()=>changeMode('login')}>{mode==='signup'?'Já tenho conta':'Voltar para entrar'}</button>}</div>}
   <p className={styles.footer}>RUPCONTROL · BY RUPTIX</p><p className={styles.legal}>{mode==='signup'?'Ao criar a conta':'Ao entrar'}, você concorda com os <a href="/termos">Termos de Uso</a> e a <a href="/privacidade">Política de Privacidade</a>.</p>
  </form></section>
 </main>
}
