"use client";
import {useEffect,useState} from "react";
import {Check,Plus,Search,Users,X} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import ModuleShell from "../_components/ModuleShell";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function ClientsContent({workspace}){const [items,setItems]=useState([]),[debts,setDebts]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[error,setError]=useState("");
 async function load(){setLoading(true);const [c,d]=await Promise.all([supabase.from("clients").select("*").eq("tenant_id",workspace.tenant.id).order("created_at",{ascending:false}),supabase.from("appointment_payments").select("id,client_id,amount_cents,created_at,services(name)").eq("tenant_id",workspace.tenant.id).eq("status","open").order("created_at",{ascending:false})]);setItems(c.data||[]);setDebts(d.data||[]);setLoading(false)}
 useEffect(()=>{load()},[workspace.tenant.id]);const filtered=items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())||x.phone?.includes(query));const debtFor=id=>debts.filter(d=>d.client_id===id),total=id=>debtFor(id).reduce((s,d)=>s+d.amount_cents,0);
 async function settle(id,method){setError("");const {error}=await supabase.rpc("settle_client_account",{t:workspace.tenant.id,p_payment:id,m:method});if(error)return setError(error.message);await load();if(selected)setSelected(items.find(x=>x.id===selected.id)||selected)}
 return <><section className="box"><div className="module-toolbar"><div><h2>Base de clientes</h2><p>{items.length} pessoas cadastradas</p></div><label className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente"/></label></div>{error&&<div className="form-alert error">{error}</div>}{loading?<p className="empty">Carregando...</p>:filtered.length===0?<div className="empty-state"><Users/><strong>Nenhum cliente encontrado</strong></div>:<div className="data-list">{filtered.map(x=><article key={x.id}><span className="client-avatar">{x.name[0]}</span><div><strong>{x.name}</strong><small>{x.phone||x.whatsapp||"Sem telefone"} · {x.email||"Sem e-mail"}</small></div>{total(x.id)>0?<button className="client-debt" onClick={()=>setSelected(x)}>Em aberto {money(total(x.id))}</button>:<span className="pill confirmed">Em dia</span>}</article>)}</div>}</section>{selected&&<div className="checkout-backdrop"><div className="checkout-modal"><button className="checkout-close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">CONTA DO CLIENTE</p><h2>{selected.name}</h2><strong className="checkout-total">{money(total(selected.id))}</strong>{debtFor(selected.id).map(d=><div className="debt-row" key={d.id}><div><strong>{d.services?.name||"Atendimento"}</strong><small>{new Date(d.created_at).toLocaleDateString("pt-BR")} · {money(d.amount_cents)}</small></div><div className="debt-pay"><button onClick={()=>settle(d.id,"pix")}>PIX</button><button onClick={()=>settle(d.id,"cash")}>Dinheiro</button><button onClick={()=>settle(d.id,"credit")}>Crédito</button><button onClick={()=>settle(d.id,"debit")}>Débito</button></div></div>)}{debtFor(selected.id).length===0&&<div className="form-alert success"><Check size={14}/> Cliente sem valores em aberto.</div>}</div></div>}</>}
export default function ClientsPage(){return <ModuleShell title="Clientes" eyebrow="Relacionamento" action={<a className="primary" href="/dashboard/clientes/novo"><Plus size={18}/> Novo cliente</a>}>{workspace=><ClientsContent workspace={workspace}/>}</ModuleShell>}