"use client";
import {useEffect,useState} from "react";
import {Clock,ExternalLink,Instagram,Save,Settings,MessageCircle,MapPin,Image as ImageIcon,CheckCircle2,CalendarDays,Coffee} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import ModuleShell from "../_components/ModuleShell";
const days=[[1,"Segunda"],[2,"Terça"],[3,"Quarta"],[4,"Quinta"],[5,"Sexta"],[6,"Sábado"],[0,"Domingo"]];
const mins=v=>{const [h,m]=v.split(":").map(Number);return h*60+m};
function SettingsContent({workspace}){const t=workspace.tenant,[media,setMedia]=useState({logo_url:t.logo_url||"",cover_url:t.cover_url||""}),[units,setUnits]=useState([]),[barbers,setBarbers]=useState([]),[services,setServices]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{Promise.all([supabase.from("units").select("*").eq("tenant_id",t.id).eq("active",true),supabase.from("barbers").select("*").eq("tenant_id",t.id).eq("active",true),supabase.from("services").select("*").eq("tenant_id",t.id).eq("active",true)]).then(([u,b,s])=>{setUnits(u.data||[]);setBarbers(b.data||[]);setServices(s.data||[])})},[t.id]);
 async function uploadImage(e,field){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sessão expirada. Entre novamente.");const body=new FormData();body.append("file",file);body.append("tenant_id",t.id);body.append("field",field);const res=await fetch("/api/media/upload",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`},body});const out=await res.json();if(!res.ok)throw new Error(out.error||"Não foi possível enviar a imagem.");setMedia(m=>({...m,[field]:out.url}));setMessage("Imagem enviada. Clique em Salvar alterações.")}catch(err){setError(err.message||"Não foi possível enviar a imagem.")}finally{setBusy(false)}}
 async function connectInstagram(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;window.location.href="/api/instagram/connect?tenant="+encodeURIComponent(t.id)+"&token="+encodeURIComponent(session.access_token)}
 async function saveSite(e){e.preventDefault();setBusy(true);setError("");setMessage("");const f=new FormData(e.currentTarget),p=Object.fromEntries(f);p.logo_url=media.logo_url;p.cover_url=media.cover_url;p.public_site_enabled=f.get("public_site_enabled")==="on";const {error}=await supabase.rpc("save_site_settings",{t:t.id,p});setBusy(false);if(error)setError(error.message);else setMessage("Site público atualizado.")}
 async function savePayment(e){e.preventDefault();setBusy(true);setError("");setMessage("");const f=new FormData(e.currentTarget),p=Object.fromEntries(f);const {error}=await supabase.rpc("save_payment_settings",{t:t.id,p});setBusy(false);if(error)setError(error.message);else setMessage("Configurações de cobrança atualizadas.")}
 async function saveHours(e){e.preventDefault();setBusy(true);setError("");setMessage("");const f=new FormData(e.currentTarget),barber=f.get("barber"),unit=f.get("unit"),start=mins(f.get("start")),end=mins(f.get("end")),lunchStart=f.get("lunch_start")?mins(f.get("lunch_start")):null,lunchEnd=f.get("lunch_end")?mins(f.get("lunch_end")):null,windows=[];for(const d of f.getAll("days").map(Number)){if(lunchStart!==null&&lunchEnd!==null&&lunchStart>start&&lunchEnd<end){windows.push({unit_id:unit,weekday:d,start_min:start,end_min:lunchStart,step_min:15},{unit_id:unit,weekday:d,start_min:lunchEnd,end_min:end,step_min:15})}else windows.push({unit_id:unit,weekday:d,start_min:start,end_min:end,step_min:15})}let r=await supabase.rpc("save_record",{t:t.id,k:"assignment",p:{barber_id:barber,unit_id:unit}});if(!r.error)for(const s of services){r=await supabase.rpc("save_record",{t:t.id,k:"qualification",p:{barber_id:barber,service_id:s.id}});if(r.error)break}if(!r.error)r=await supabase.rpc("save_week",{t:t.id,b:barber,p:windows});setBusy(false);if(r.error)setError(r.error.message);else setMessage("Horários publicados. O site já usa esta disponibilidade.")}
 return <><form className="social-settings form" onSubmit={saveSite}>
 <div className="social-settings-head"><div><h2>Site e Redes Sociais</h2><p>Configure as informações que aparecem no seu site público de agendamento.</p></div><button className="primary" disabled={busy}><Save size={17}/>Salvar alterações</button></div>
 <section className="social-card"><h3>Informações da barbearia</h3><p>Essas informações serão exibidas no seu site público de agendamento.</p><div className="form-grid"><label>Nome da barbearia<input name="name" defaultValue={t.name} required/></label><label>Telefone<input name="phone" defaultValue={t.phone}/></label><label>Endereço completo<input name="address" defaultValue={t.address}/></label><label>Descrição<textarea name="description" defaultValue={t.description}/></label></div><label>Informações importantes<textarea name="public_info" defaultValue={t.public_info}/></label><label className="check-line"><input name="public_site_enabled" type="checkbox" defaultChecked={t.public_site_enabled!==false}/> Site público ativo</label></section>
 <section className="social-card"><h3>Redes sociais</h3><p>Adicione suas redes para aparecerem no site de agendamento.</p><div className="social-network-grid"><div className="network-box"><div className="network-title"><Instagram/><strong>Instagram</strong></div><input name="instagram" defaultValue={t.instagram} placeholder="@sua_barbearia"/><small className="network-ok"><CheckCircle2/> {t.instagram?"Instagram configurado":"Informe o @ do Instagram"}</small><div className="network-actions">{t.instagram&&<a className="secondary-action" href={"https://www.instagram.com/"+String(t.instagram).replace(/^@/,"")} target="_blank" rel="noreferrer"><Instagram size={16}/>Ver perfil</a>}<button type="button" className="secondary-action" onClick={connectInstagram}>Conectar feed</button></div></div><div className="network-box"><div className="network-title"><MessageCircle/><strong>WhatsApp</strong></div><input name="whatsapp" defaultValue={t.whatsapp} placeholder="+55 11 99999-9999"/><small className="network-ok"><CheckCircle2/> {t.whatsapp?"WhatsApp configurado":"Informe o WhatsApp"}</small>{t.whatsapp&&<a className="secondary-action" href={"https://wa.me/55"+String(t.whatsapp).replace(/\D/g,"").replace(/^55/,"")} target="_blank" rel="noreferrer"><MessageCircle size={16}/>Testar WhatsApp</a>}</div></div></section>
 <section className="social-card"><h3>Imagens</h3><p>Logo e imagem de capa que aparecem no site de agendamento.</p><div className="social-network-grid"><label className="upload-box"><ImageIcon/><strong>Logo da barbearia</strong>{media.logo_url&&<img src={media.logo_url} alt="Logo"/>}<input name="logo_url" type="hidden" value={media.logo_url} readOnly/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadImage(e,"logo_url")}/></label><label className="upload-box"><ImageIcon/><strong>Imagem de capa</strong>{media.cover_url&&<img src={media.cover_url} alt="Capa"/>}<input name="cover_url" type="hidden" value={media.cover_url} readOnly/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadImage(e,"cover_url")}/></label></div></section>
 {message&&<div className="form-alert success">{message}</div>}{error&&<div className="form-alert error">{error}</div>}
 <div className="site-status"><CheckCircle2/><div><strong>Seu site está {t.public_site_enabled===false?"desativado":"ativo"}</strong><small>Confira como seus clientes veem sua página.</small></div><a className="site-link" target="_blank" href={`/agendar/${t.slug}`}><ExternalLink size={15}/>Abrir site de agendamento</a></div>
 </form>
 <div className="settings-secondary"><form className="box form hours-premium" onSubmit={saveHours}><div className="hours-title"><span><CalendarDays/></span><div><h2>Horários de funcionamento</h2><p>Defina os dias, horários e intervalos da sua barbearia.</p></div></div><div className="hours-selectors"><label>Unidade<select name="unit" required><option value="">Selecione</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Profissional<select name="barber" required><option value="">Selecione</option>{barbers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><fieldset className="hours-days"><legend>Dias trabalhados</legend>{days.map(([v,n])=><label key={v}><span>{n.slice(0,3)}</span><input name="days" type="checkbox" value={v} defaultChecked={v>0&&v<7}/><i/></label>)}</fieldset><div className="hours-editor"><div className="hours-editor-head"><span><CalendarDays/></span><strong>Horário de atendimento</strong></div><div className="hours-time-grid"><label>Horário de entrada<div><Clock/><input name="start" type="time" defaultValue="09:00" required/></div></label><label>Horário de saída<div><Clock/><input name="end" type="time" defaultValue="19:00" required/></div></label></div><div className="hours-break-title"><Coffee/><div><strong>Intervalo</strong><small>Defina o horário de almoço ou pausa.</small></div></div><div className="hours-time-grid"><label>Início do intervalo<div><Clock/><input name="lunch_start" type="time" defaultValue="12:00"/></div></label><label>Fim do intervalo<div><Clock/><input name="lunch_end" type="time" defaultValue="13:00"/></div></label></div></div><button className="primary form-submit hours-publish" disabled={busy}><Save/>Publicar horários<small>Atualiza a disponibilidade no site de agendamento</small></button></form>
 <form className="box form payment-settings" onSubmit={savePayment}><h2><Save size={17}/> Cobrança e PIX</h2><div className="form-grid"><label>Chave PIX<input name="pix_key" defaultValue={t.pix_key||""} required/></label><label>Nome do recebedor<input name="pix_name" maxLength="25" defaultValue={t.pix_name||t.name||""} required/></label><label>Cidade<input name="pix_city" maxLength="15" defaultValue={t.pix_city||"SAO PAULO"} required/></label></div><button className="primary form-submit" disabled={busy}><Save size={17}/>Salvar cobrança</button></form></div></>}
export default function SettingsPage(){return <ModuleShell title="Configurações" eyebrow="Site e horários">{workspace=><SettingsContent workspace={workspace}/>}</ModuleShell>}
