import {createHmac,timingSafeEqual} from "node:crypto";
import {NextResponse} from "next/server";import {createClient} from "@supabase/supabase-js";
const admin=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const norm=s=>String(s||"").replace(/\D/g,"");
const dayRange=(kind)=>{const now=new Date(),d=new Date(now.toLocaleString("en-US",{timeZone:"America/Sao_Paulo"}));if(kind==="tomorrow")d.setDate(d.getDate()+1);const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return y+"-"+m+"-"+day};
async function send(phone,text){const id=process.env.WHATSAPP_PHONE_NUMBER_ID,token=process.env.WHATSAPP_ACCESS_TOKEN;if(!id||!token)return;await fetch("https://graph.facebook.com/v23.0/"+id+"/messages",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:phone,type:"text",text:{body:text}})})}
export async function GET(req){const u=new URL(req.url);if(u.searchParams.get("hub.mode")==="subscribe"&&u.searchParams.get("hub.verify_token")===process.env.WHATSAPP_VERIFY_TOKEN)return new Response(u.searchParams.get("hub.challenge")||"",{status:200});return new Response("Forbidden",{status:403})}
export async function POST(req){const secret=process.env.WHATSAPP_APP_SECRET;if(!secret)return NextResponse.json({error:"Integração WhatsApp não configurada."},{status:503});const raw=await req.text(),sig=req.headers.get("x-hub-signature-256")||"",expected="sha256="+createHmac("sha256",secret).update(raw).digest("hex");if(sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return NextResponse.json({error:"Assinatura inválida."},{status:401});let body;try{body=JSON.parse(raw)}catch{return NextResponse.json({error:"JSON inválido."},{status:400})}const msg=body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0];if(!msg||msg.type!=="text")return NextResponse.json({ok:true});const phone=norm(msg.from),text=String(msg.text?.body||"").trim().toLowerCase(),db=admin(),phoneNumberId=body?.entry?.[0]?.changes?.[0]?.value?.metadata?.phone_number_id;
 const {data:members}=await db.from("memberships").select("tenant_id,user_id,name,role,whatsapp,tenants(name)").eq("active",true).eq("whatsapp",phone).limit(2);
 if(!members?.length){
  const {data:number}=await db.from("whatsapp_numbers").select("tenant_id,tenants(name,address,whatsapp)").eq("phone_number_id",phoneNumberId||"").eq("active",true).maybeSingle();
  if(!number){await send(phone,"Olá! Este número ainda não está vinculado a uma barbearia no Barber Flow.");return NextResponse.json({ok:true})}
  const tenant=number.tenant_id,{data:session}=await db.from("whatsapp_booking_sessions").select("*").eq("phone",phone).eq("tenant_id",tenant).maybeSingle();
  let st=session?.state||"start",d=session?.data||{};
  if(/^(oi|olá|ola|menu|início|inicio)$/.test(text)){st="start";d={}}
  if(st==="start"){const {data:ss}=await db.from("services").select("id,name,price_cents").eq("tenant_id",tenant).eq("active",true).order("name");d={services:ss||[]};await db.from("whatsapp_booking_sessions").upsert({phone,tenant_id:tenant,state:"service",data:d,updated_at:new Date().toISOString()});await send(phone,"Olá! Sou o assistente de agendamento da "+(number.tenants?.name||"barbearia")+".\n\nEscolha um serviço:\n"+(ss||[]).map((x,i)=>(i+1)+". "+x.name+" — "+(x.price_cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})).join("\n")+"\n\nDigite o número da opção.");return NextResponse.json({ok:true})}
  if(st==="service"){const s=d.services?.[Number(text)-1];if(!s){await send(phone,"Opção inválida. Digite o número do serviço.");return NextResponse.json({ok:true})}const {data:bs}=await db.from("barber_services").select("barber_id,barbers(id,name,active)").eq("tenant_id",tenant).eq("service_id",s.id);const barbers=(bs||[]).map(x=>x.barbers).filter(x=>x?.active);d={...d,service:s,barbers};await db.from("whatsapp_booking_sessions").upsert({phone,tenant_id:tenant,state:"barber",data:d,updated_at:new Date().toISOString()});await send(phone,"Escolha o profissional:\n"+barbers.map((x,i)=>(i+1)+". "+x.name).join("\n")+"\n\nDigite o número da opção.");return NextResponse.json({ok:true})}
  if(st==="barber"){const b=d.barbers?.[Number(text)-1];if(!b){await send(phone,"Opção inválida. Digite o número do profissional.");return NextResponse.json({ok:true})}d={...d,barber:b};await db.from("whatsapp_booking_sessions").upsert({phone,tenant_id:tenant,state:"date",data:d,updated_at:new Date().toISOString()});await send(phone,"Qual dia você prefere? Envie no formato DD/MM, por exemplo 25/09.");return NextResponse.json({ok:true})}
  if(st==="date"){const mt=text.match(/^(\d{1,2})\/(\d{1,2})$/);if(!mt){await send(phone,"Envie a data no formato DD/MM.");return NextResponse.json({ok:true})}const now=new Date(),date=now.getFullYear()+"-"+String(mt[2]).padStart(2,"0")+"-"+String(mt[1]).padStart(2,"0");const {data:units}=await db.from("barber_units").select("unit_id").eq("tenant_id",tenant).eq("barber_id",d.barber.id).limit(1);const unit=units?.[0]?.unit_id;if(!unit){await send(phone,"Esse profissional ainda não possui unidade configurada.");return NextResponse.json({ok:true})}const {data:slots,error}=await db.rpc("public_available_slots_multi",{p_slug:null,p_unit:unit,p_barber:d.barber.id,p_services:[d.service.id],p_date:date});if(error||!slots?.length){await send(phone,"Não encontrei horários disponíveis nessa data. Envie outra data em DD/MM.");return NextResponse.json({ok:true})}d={...d,date,unit,slots};await db.from("whatsapp_booking_sessions").upsert({phone,tenant_id:tenant,state:"slot",data:d,updated_at:new Date().toISOString()});await send(phone,"Horários disponíveis:\n"+slots.slice(0,12).map((x,i)=>(i+1)+". "+new Date(x.starts_at||x.start_at||x).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})).join("\n")+"\n\nDigite o número do horário.");return NextResponse.json({ok:true})}
  await send(phone,"Digite MENU para iniciar um novo agendamento.");return NextResponse.json({ok:true})
 }
 if(members.length>1){await send(phone,"Este número está vinculado a mais de uma conta. Ajuste o cadastro no Barber Flow.");return NextResponse.json({ok:true})}
 const m=members[0];if(m.role!=="barber"&&m.role!=="owner"){await send(phone,"A consulta de agenda pelo WhatsApp está disponível para profissionais da barbearia.");return NextResponse.json({ok:true})}
 const {data:b}=await db.from("barbers").select("id").eq("tenant_id",m.tenant_id).eq("user_id",m.user_id).eq("active",true).maybeSingle();if(!b){await send(phone,"Seu usuário ainda não está vinculado a um profissional ativo.");return NextResponse.json({ok:true})}
 let kind=text.includes("amanh")?"tomorrow":"today",date=dayRange(kind);const dm=text.match(/\b(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?\b/);if(dm){const now=new Date(),yy=dm[3]?Number(dm[3].length===2?"20"+dm[3]:dm[3]):now.getFullYear();date=yy+"-"+String(dm[2]).padStart(2,"0")+"-"+String(dm[1]).padStart(2,"0")}
 const start=new Date(date+"T00:00:00-03:00").toISOString(),end=new Date(date+"T23:59:59-03:00").toISOString();const {data:a}=await db.from("appointments").select("starts_at,status,clients(name),services(name)").eq("tenant_id",m.tenant_id).eq("barber_id",b.id).gte("starts_at",start).lte("starts_at",end).neq("status","cancelled").order("starts_at");
 let reply;if(text.includes("próximo")||text.includes("proximo")){const next=(a||[]).find(x=>new Date(x.starts_at)>new Date());reply=next?"Seu próximo cliente é "+next.clients?.name+" às "+new Date(next.starts_at).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})+" — "+(next.services?.name||"Atendimento")+".":"Você não tem mais atendimentos agendados nessa data."}else if(!a?.length)reply="Você não tem atendimentos agendados para "+new Date(date+"T12:00:00").toLocaleDateString("pt-BR")+".";else reply="Sua agenda — "+new Date(date+"T12:00:00").toLocaleDateString("pt-BR")+"\n\n"+a.map(x=>new Date(x.starts_at).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})+" — "+x.clients?.name+"\n"+(x.services?.name||"Atendimento")).join("\n\n")+"\n\n"+a.length+" atendimento"+(a.length===1?"":"s")+" agendado"+(a.length===1?"":"s")+".";
 await db.from("whatsapp_bot_logs").insert({tenant_id:m.tenant_id,user_id:m.user_id,phone,direction:"in",message:text});await send(phone,reply);await db.from("whatsapp_bot_logs").insert({tenant_id:m.tenant_id,user_id:m.user_id,phone,direction:"out",message:reply});return NextResponse.json({ok:true})}