"use client";
import {useEffect,useState} from "react";
import {CalendarDays,Check,Copy,RefreshCw,X} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import QRCode from "qrcode";
import ModuleShell from "../_components/ModuleShell";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const crc16=s=>{let crc=0xffff;for(let i=0;i<s.length;i++){crc^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=(crc&0x8000)?(crc<<1)^0x1021:crc<<1;crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,"0")};
const field=(id,value)=>id+String(value.length).padStart(2,"0")+value;
function pixPayload(key,name,city,amount,txid){const clean=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Za-z0-9 .-]/g,"").toUpperCase();const merchant=field("00","BR.GOV.BCB.PIX")+field("01",String(key).trim());let p=field("00","01")+field("26",merchant)+field("52","0000")+field("53","986")+field("54",(amount/100).toFixed(2))+field("58","BR")+field("59",clean(name).slice(0,25)||"BARBEARIA")+field("60",clean(city).slice(0,15)||"SAO PAULO")+field("62",field("05",clean(txid).replace(/[^A-Z0-9]/g,"").slice(0,25)||"***"))+"6304";return p+crc16(p)}
function Agenda({workspace}){const [items,setItems]=useState([]),[paid,setPaid]=useState(new Set()),[loading,setLoading]=useState(true),[checkout,setCheckout]=useState(null),[method,setMethod]=useState("pix"),[payload,setPayload]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[qr,setQr]=useState("");
 async function load(){setLoading(true);const {data}=await supabase.from("appointments").select("id,starts_at,ends_at,status,source,price_cents,clients(name,phone),barbers(name),services(name),units(name)").eq("tenant_id",workspace.tenant.id).gte("starts_at",new Date(new Date().setHours(0,0,0,0)).toISOString()).order("starts_at").limit(200);const ids=(data||[]).map(x=>x.id);let done=[];if(ids.length){const r=await supabase.from("appointment_payments").select("appointment_id").eq("tenant_id",workspace.tenant.id).in("appointment_id",ids).neq("status","cancelled");done=(r.data||[]).map(x=>x.appointment_id)}setPaid(new Set(done));setItems(data||[]);setLoading(false)}
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[workspace.tenant.id]);
 function openCheckout(x){setCheckout(x);setMethod("pix");setPayload("");setQr("");setError("");setTimeout(async()=>{const t=workspace.tenant;if(t.pix_key){const p=pixPayload(t.pix_key,t.pix_name||t.name,t.pix_city||"SAO PAULO",x.price_cents,x.id.replace(/-/g,"").slice(0,20));setPayload(p);setQr(await QRCode.toDataURL(p,{width:260,margin:1}))}},0)}
 async function choose(v){setMethod(v);setError("");setQr("");if(v==="pix"){const t=workspace.tenant;if(!t.pix_key)return setPayload("");const p=pixPayload(t.pix_key,t.pix_name||t.name,t.pix_city||"SAO PAULO",checkout.price_cents,checkout.id.replace(/-/g,"").slice(0,20));setPayload(p);setQr(await QRCode.toDataURL(p,{width:260,margin:1}))}else setPayload("")}
 async function finish(){setError("");if(method==="pix"&&!workspace.tenant.pix_key)return setError("Cadastre a chave PIX em Configurações antes de cobrar por PIX.");if(method==="pix"&&!payload)choose("pix");setBusy(true);const finalPayload=method==="pix"?(payload||pixPayload(workspace.tenant.pix_key,workspace.tenant.pix_name||workspace.tenant.name,workspace.tenant.pix_city||"SAO PAULO",checkout.price_cents,checkout.id.replace(/-/g,"").slice(0,20))):"";const {error}=await supabase.rpc("checkout_appointment",{t:workspace.tenant.id,a:checkout.id,m:method,p_pix_payload:finalPayload});setBusy(false);if(error)return setError(error.message);setCheckout(null);await load()}
 const labels={pix:"PIX",cash:"Dinheiro",credit:"Crédito",debit:"Débito",account:"Conta do cliente"};
 return <><section className="box"><div className="module-toolbar"><div><h2>Agenda em tempo real</h2><p>Agendamentos internos e do site público</p></div><button className="primary" onClick={load}><RefreshCw size={16}/>Atualizar</button></div>{loading?<p className="empty">Atualizando...</p>:items.length===0?<div className="empty-state"><CalendarDays/><strong>Nenhum agendamento</strong></div>:<div className="data-list">{items.map(x=><article key={x.id}><span className="service-icon"><CalendarDays/></span><div><strong>{new Date(x.starts_at).toLocaleString("pt-BR")} · {x.clients?.name}</strong><small>{x.services?.name} com {x.barbers?.name} · {x.units?.name} · {money(x.price_cents)}</small></div>{paid.has(x.id)?<span className="pill completed">Finalizado</span>:x.status==="cancelled"?<span className="pill">Cancelado</span>:<button className="checkout-btn" onClick={()=>openCheckout(x)}>Finalizar atendimento</button>}</article>)}</div>}</section>{checkout&&<div className="checkout-backdrop"><div className="checkout-modal"><button className="checkout-close" onClick={()=>setCheckout(null)}><X/></button><p className="eyebrow">FINALIZAR ATENDIMENTO</p><h2>{checkout.clients?.name}</h2><p className="checkout-service">{checkout.services?.name} · {checkout.barbers?.name}</p><strong className="checkout-total">{money(checkout.price_cents)}</strong><div className="payment-methods">{Object.entries(labels).map(([v,l])=><button key={v} className={method===v?"active":""} onClick={()=>choose(v)}>{l}</button>)}</div>{method==="pix"&&<div className="pix-box">{workspace.tenant.pix_key?<><{qr&&<img className="pix-qr" src={qr} alt="QR Code PIX"/>}<small>PIX Copia e Cola</small><textarea readOnly value={payload||pixPayload(workspace.tenant.pix_key,workspace.tenant.pix_name||workspace.tenant.name,workspace.tenant.pix_city||"SAO PAULO",checkout.price_cents,checkout.id.replace(/-/g,"").slice(0,20))}/><button onClick={()=>navigator.clipboard.writeText(payload||pixPayload(workspace.tenant.pix_key,workspace.tenant.pix_name||workspace.tenant.name,workspace.tenant.pix_city||"SAO PAULO",checkout.price_cents,checkout.id.replace(/-/g,"").slice(0,20)))}><Copy size={15}/>Copiar PIX</button><p>Confirme abaixo depois de receber o pagamento.</p></>:<p>Cadastre a chave PIX em Configurações.</p>}</div>}{method==="account"&&<div className="account-warning">O atendimento será finalizado e o valor ficará em aberto na conta deste cliente.</div>}{error&&<div className="form-alert error">{error}</div>}<button className="primary checkout-confirm" disabled={busy} onClick={finish}><Check size={17}/>{method==="account"?"Registrar na conta do cliente":"Confirmar pagamento em "+labels[method]}</button></div></div>}</>}
export default function AgendaPage(){return <ModuleShell title="Agenda" eyebrow="Atendimentos">{workspace=><Agenda workspace={workspace}/>}</ModuleShell>}