"use client";
import {notify} from "../../../lib/notify";
import { useEffect,useState } from "react";
import { Check,Pencil,Plus,Briefcase,Search,X } from "lucide-react";
import { supabase } from "../../../lib/supabase";
import ModuleShell from "../_components/ModuleShell";
const money=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const plain=v=>String(v||"").normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase();
function ServicesContent({workspace}){const role=workspace.membership?.role,canEdit=role==="owner"||(["manager","reception"].includes(role)&&workspace.membership?.permissions?.includes("services"));const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const {data,error}=await supabase.from("services").select("*").eq("tenant_id",workspace.tenant.id).order("name");setError(error?.message||"");setItems(data||[]);setLoading(false)}
 useEffect(()=>{load()},[workspace.tenant.id]);
 async function saveEdit(e){e.preventDefault();if(busy)return;setError("");const f=new FormData(e.currentTarget),p={id:editing.id,name:String(f.get("name")||"").trim(),description:f.get("description")||"",duration:Number(f.get("duration")),price_cents:Math.round(Number(f.get("price"))*100),commission_bps:Math.round(Number(f.get("commission")||0)*100),active:f.get("active")==="on"};if(!p.name)return setError("Informe o nome do serviço.");if(!Number.isFinite(p.price_cents)||p.price_cents<0)return setError("Informe um preço válido.");setBusy(true);const {error}=await supabase.rpc("save_record",{t:workspace.tenant.id,k:"service",p});setBusy(false);if(error)return setError(error.message);setEditing(null);notify("Serviço atualizado com sucesso.");await load()}
 const filtered=items.filter(x=>plain(x.name).includes(plain(query))),activeCount=items.filter(x=>x.active).length;
 return <><section className="box"><div className="module-toolbar"><div><h2>Catálogo de serviços</h2><p>{items.length} serviços cadastrados · {activeCount} ativos</p></div><label className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar serviço"/></label></div>{error&&!editing&&<div className="form-alert error">{error}</div>}{loading?<p className="empty">Carregando...</p>:filtered.length===0?<div className="empty-state"><Briefcase/><strong>{items.length?"Nenhum serviço encontrado":"Nenhum serviço cadastrado"}</strong></div>:<div className="data-list">{filtered.map(x=><article key={x.id}><span className="service-icon"><Briefcase size={17}/></span><div><strong>{x.name}</strong><small>{x.duration} minutos · comissão {(Number(x.commission_bps||0)/100).toFixed(0)}%</small></div><strong>{money(x.price_cents)}</strong>{canEdit&&<button className="client-edit" onClick={()=>{setError("");setEditing(x)}}><Pencil size={14}/> Editar</button>}<span className={`pill ${x.active?"confirmed":""}`}>{x.active?"ativo":"inativo"}</span></article>)}</div>}</section>
 {editing&&canEdit&&<div className="checkout-backdrop"><form className="checkout-modal client-edit-modal" onSubmit={saveEdit}><button type="button" className="checkout-close" onClick={()=>setEditing(null)}><X/></button><p className="eyebrow">CATÁLOGO</p><h2>Editar serviço</h2><div className="quick-sale-form"><label className="wide">Nome<input name="name" defaultValue={editing.name} required/></label><label>Preço (R$)<input name="price" type="number" min="0" step="0.01" defaultValue={(Number(editing.price_cents||0)/100).toFixed(2)} required/></label><label>Duração (minutos)<input name="duration" type="number" min="5" max="480" defaultValue={editing.duration} required/></label><label>Comissão (%)<input name="commission" type="number" min="0" max="100" step="0.01" defaultValue={Number(editing.commission_bps||0)/100}/></label><label className="inventory-check"><input name="active" type="checkbox" defaultChecked={editing.active}/> Serviço ativo (aparece na agenda e no site)</label><label className="wide">Descrição<input name="description" defaultValue={editing.description||""}/></label></div>{error&&<div className="form-alert error">{error}</div>}<button className="primary checkout-confirm" disabled={busy}><Check size={16}/>{busy?"Salvando...":"Salvar alterações"}</button></form></div>}</>}
export default function ServicesPage(){return <ModuleShell title="Serviços" eyebrow="Catálogo" action={<a className="primary" href="/dashboard/servicos/novo"><Plus size={18}/> Novo serviço</a>}>{workspace=><ServicesContent workspace={workspace}/>}</ModuleShell>}
