"use client";
import {useEffect,useState} from "react";
import QRCode from "qrcode";
import ModuleShell from "../_components/ModuleShell";
import {Check,Copy,ShieldCheck} from "lucide-react";
const KEY="sonorag4@hotmail.com",field=(id,v)=>id+String(v.length).padStart(2,"0")+v;
const clean=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Za-z0-9 ]/g,"").toUpperCase();
function crc16(s){let c=65535;for(let i=0;i<s.length;i++){c^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)c=(c&32768)?(c<<1)^4129:c<<1;c&=65535}return c.toString(16).toUpperCase().padStart(4,"0")}
function payload(name,cents){const d=("BARBER FLOW "+clean(name)).slice(0,72),m=field("00","BR.GOV.BCB.PIX")+field("01",KEY)+field("02",d),a=(Number(cents||0)/100).toFixed(2),b=field("00","01")+field("26",m)+field("52","0000")+field("53","986")+field("54",a)+field("58","BR")+field("59","BARBER FLOW")+field("60","SAO PAULO")+field("62",field("05","***"))+"6304";return b+crc16(b)}
function PixPay({pix}){const [copied,setCopied]=useState(false),[qr,setQr]=useState("");useEffect(()=>{QRCode.toDataURL(pix,{width:240,margin:1}).then(setQr).catch(()=>setQr(""))},[pix]);return <div className="monthly-pix"><div className="monthly-qr">{qr&&<img src={qr} alt="QR Code PIX" width="220" height="220"/>}</div><p>Escaneie o QR Code com o aplicativo do seu banco</p><button className="monthly-copy" type="button" onClick={async()=>{await navigator.clipboard.writeText(pix);setCopied(true);setTimeout(()=>setCopied(false),1800)}}>{copied?<><Check size={17}/> PIX copiado</>:<><Copy size={17}/> Copiar código PIX</>}</button><small><ShieldCheck size={14}/> Pagamento via PIX</small></div>}
export default function Mensalidade(){return <ModuleShell title="Mensalidade" eyebrow="Conta">{w=>{const base=w.tenant?.plans?.monthly_cents||0,surcharge=Number(w.tenant?.no_commitment_surcharge_pct||0),discount=Number(w.tenant?.discount_pct||0),discountMonths=Number(w.tenant?.discount_months||0),started=w.tenant?.discount_started_at?new Date(w.tenant.discount_started_at+"T12:00:00"):null,discountActive=discount>0&&discountMonths>0&&started&&new Date()<new Date(started.getFullYear(),started.getMonth()+discountMonths,started.getDate()),amount=Math.max(0,Math.round(base*(1+surcharge/100)*(1-(discountActive?discount:0)/100))),pix=payload(w.tenant?.name,amount),due=w.tenant?.billing_due_date?new Date(w.tenant.billing_due_date+"T12:00:00").toLocaleDateString("pt-BR"):"—";return <div className="monthly-wrap"><section className="monthly-card"><div className="monthly-plan"><span>PLANO ATUAL</span><h2>{w.tenant?.plans?.name||"Plano contratado"}</h2><p>{w.tenant?.name}</p><strong>{(amount/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}<small>/mês</small></strong><div className="monthly-due"><span>Próximo vencimento</span><b>{due}</b></div></div><div className="monthly-payment"><span className="monthly-label">PAGAR MENSALIDADE</span><h3>Pagamento por PIX</h3><p>Use o QR Code ou copie o código para pagar.</p><PixPay pix={pix}/></div></section></div>}}</ModuleShell>}