alter table public.barber_services enable row level security;
revoke all on public.barber_services from anon;
revoke insert,update,delete,truncate,references,trigger on public.barber_services from authenticated;
grant select on public.barber_services to authenticated;
alter table public.weekly_windows enable row level security;
revoke all on public.weekly_windows from anon;
revoke insert,update,delete,truncate,references,trigger on public.weekly_windows from authenticated;
grant select on public.weekly_windows to authenticated;
alter table public.schedule_exceptions enable row level security;
revoke all on public.schedule_exceptions from anon;
revoke insert,update,delete,truncate,references,trigger on public.schedule_exceptions from authenticated;
grant select on public.schedule_exceptions to authenticated;
alter table public.tenants enable row level security;
revoke all on public.tenants from anon;
revoke insert,update,delete,truncate,references,trigger on public.tenants from authenticated;
grant select on public.tenants to authenticated;
alter table public.plans enable row level security;
revoke all on public.plans from anon;
revoke insert,update,delete,truncate,references,trigger on public.plans from authenticated;
grant select on public.plans to authenticated;
alter table public.memberships enable row level security;
revoke all on public.memberships from anon;
revoke insert,update,delete,truncate,references,trigger on public.memberships from authenticated;
grant select on public.memberships to authenticated;
alter table public.units enable row level security;
revoke all on public.units from anon;
revoke insert,update,delete,truncate,references,trigger on public.units from authenticated;
grant select on public.units to authenticated;
alter table public.barbers enable row level security;
revoke all on public.barbers from anon;
revoke insert,update,delete,truncate,references,trigger on public.barbers from authenticated;
grant select on public.barbers to authenticated;
alter table public.barber_units enable row level security;
revoke all on public.barber_units from anon;
revoke insert,update,delete,truncate,references,trigger on public.barber_units from authenticated;
grant select on public.barber_units to authenticated;
alter table public.clients enable row level security;
revoke all on public.clients from anon;
revoke insert,update,delete,truncate,references,trigger on public.clients from authenticated;
grant select on public.clients to authenticated;
alter table public.services enable row level security;
revoke all on public.services from anon;
revoke insert,update,delete,truncate,references,trigger on public.services from authenticated;
grant select on public.services to authenticated;
alter table public.audit_events enable row level security;
revoke all on public.audit_events from anon;
revoke insert,update,delete,truncate,references,trigger on public.audit_events from authenticated;
grant select on public.audit_events to authenticated;
alter table public.appointments enable row level security;
revoke all on public.appointments from anon;
revoke insert,update,delete,truncate,references,trigger on public.appointments from authenticated;
grant select on public.appointments to authenticated;
