"use client";
import Link from "next/link";
import RuptixFx from "../../_components/RuptixFx";
import "../../ruptix-home.css";
import {APP_URL,SIGNUP_URL} from "../../../lib/site";
import {ArrowRight,BarChart3,CalendarDays,Check,Globe2,Instagram,MessageCircle,Scissors,ShieldCheck,Smartphone,Users,WalletCards,X,Zap} from "lucide-react";

const features=[
 ["Agenda inteligente","Horários, profissionais, serviços e disponibilidade em uma agenda centralizada.",CalendarDays],
 ["Site de agendamento","Cada barbearia ganha sua própria página pública para receber agendamentos.",Globe2],
 ["Vendas e PIX","Caixa rápido, pagamentos, vendas em conta e histórico financeiro.",WalletCards],
 ["Clientes","Cadastro, histórico e controle de valores em aberto por cliente.",Users],
 ["WhatsApp","Estrutura preparada para atendimento e agendamentos pelo WhatsApp.",MessageCircle],
 ["Instagram","Conecte a presença digital da barbearia ao ecossistema RupControl.",Instagram],
];
export default function ProductPage(){return <main className="ruptix-site rx rx-barber">
 <RuptixFx/><div className="rx-aurora" aria-hidden="true"><i/><i/><i/><i/></div><div className="rx-grid" aria-hidden="true"/>
 <nav className="rp-nav"><Link href="/" className="rp-logo">RUPTIX<span>.</span></Link><div><a href="#produto">Produto</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><span className="rp-nav-actions"><a href={APP_URL+"/login"} className="rp-login">Entrar</a><a href={SIGNUP_URL} className="rp-primary">Teste grátis</a></span></nav>
 <section className="rp-hero" id="produto"><div className="rp-glow"/><div className="rp-hero-copy"><span className="rp-tag"><Zap size={14}/> 14 DIAS GRÁTIS · TECNOLOGIA PARA BARBEARIAS</span><h1>Seu negócio.<br/><em>Em outro nível.</em></h1><p>Conheça o <strong>RupControl</strong>, a plataforma da Ruptix criada para centralizar agenda, clientes, equipe, vendas e presença digital da sua barbearia.</p><div className="rp-actions"><a href={SIGNUP_URL} className="rp-primary">Testar grátis por 14 dias <ArrowRight/></a><a href="#planos" className="rp-secondary">Ver planos</a></div><p className="rp-trial-note">Sem cartão de crédito. O pagamento só começa depois dos 14 dias, se você quiser continuar.</p><div className="rp-trust"><span><ShieldCheck/>Gestão centralizada</span><span><Smartphone/>Feito para celular</span><span><BarChart3/>Controle do negócio</span></div></div>
 <div className="rp-product"><div className="rp-window"><div className="rp-window-top"><i/><i/><i/><span>RUPCONTROL</span></div><div className="rp-demo"><aside><b>RC</b><span>Visão geral</span><span>Agenda</span><span>Clientes</span><span>Vendas</span><span>Equipe</span></aside><section><small>VISÃO GERAL</small><h3>Bom dia.</h3><div className="rp-demo-stats"><div><small>Agendamentos</small><b>24</b></div><div><small>Vendas</small><b>R$ 2.480</b></div><div><small>Clientes</small><b>186</b></div></div><div className="rp-demo-card"><span>Próximos agendamentos</span><p>09:30 · Corte + Barba</p><p>10:15 · Degradê</p><p>11:00 · Corte Premium</p></div></section></div></div><div className="rp-floating"><Scissors/><div><b>RupControl</b><span>by Ruptix</span></div></div></div></section>
 <section className="rp-strip"><span>AGENDA</span><i/> <span>VENDAS</span><i/> <span>CLIENTES</span><i/> <span>PIX</span><i/> <span>WHATSAPP</span><i/> <span>RELATÓRIOS</span></section>
 <section className="rp-section" id="recursos"><div className="rp-section-head"><span>UM SISTEMA. TODA A OPERAÇÃO.</span><h2>Menos improviso.<br/>Mais controle.</h2><p>O RupControl reúne as ferramentas essenciais da operação em uma experiência simples para o proprietário e sua equipe.</p></div><div className="rp-features">{features.map(([t,p,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="rp-showcase"><div><span>PARA QUEM QUER CRESCER</span><h2>Da cadeira ao financeiro.</h2><p>Tenha uma visão mais clara da rotina da barbearia, organize a equipe e ofereça uma experiência moderna para seus clientes.</p></div><div className="rp-checks">{["Agenda individual por profissional","Página exclusiva de agendamento","Caixa rápido e formas de pagamento","Conta do cliente e controle de pendências","Painel administrativo e gestão da equipe","Experiência responsiva no celular"].map(x=><p key={x}><Check/>{x}</p>)}</div></section>
 <section className="rp-section rp-plans" id="planos"><div className="rp-section-head center"><span>14 DIAS GRÁTIS EM QUALQUER PLANO</span><h2>Teste grátis.<br/>Pague só depois.</h2><p>Crie sua conta e use o RupControl por 14 dias, sem cartão de crédito. Você escolhe o plano no cadastro e pode trocar até o primeiro pagamento.</p></div><div className="rp-plan-grid">{[
 ["Starter","R$ 89,90","Só a gestão interna e o financeiro.",["Proprietário + 1 perfil","Vendas, caixa, clientes, financeiro e estoque","-Sem site de agendamento","-Sem robô do WhatsApp"]],
 ["Pro","R$ 149,90","Operação completa para uma unidade.",["Tudo do sistema","Proprietário + 10 perfis","Agenda e site de agendamento","WhatsApp e gestão completa"]],
 ["Pro + Filiais","R$ 239,90","Para operar matriz e filiais.",["Tudo do Pro","Proprietário + 10 perfis","Múltiplas unidades","+ R$ 49,90 por filial adicional"]]
 ].map(([n,price,d,list],i)=><article className={i===1?"featured":""} key={n}>{i===1&&<b className="rp-popular">MAIS ESCOLHIDO</b>}<small>RUPCONTROL</small><h3>{n}</h3><strong style={{display:"block",fontSize:"1.55rem",margin:"8px 0"}}>{price}<small style={{fontSize:".75rem",fontWeight:500}}> / mês</small></strong><p>{d}</p><ul>{list.map(x=>x.startsWith("-")?<li key={x} className="rp-missing"><X/>{x.slice(1)}</li>:<li key={x}><Check/>{x}</li>)}</ul><a href={SIGNUP_URL}>Começar 14 dias grátis <ArrowRight/></a></article>)}</div><p className="rp-contract">Contrato anual pelo valor normal do plano. Opção sem fidelidade disponível com acréscimo de 15% na mensalidade.</p></section>
 <section className="rp-cta"><div><span>14 DIAS GRÁTIS</span><h2>Teste o RupControl.</h2><p>Crie sua conta agora e use o RupControl por 14 dias, sem cartão de crédito.</p></div><a href={SIGNUP_URL}>Criar conta grátis <ArrowRight/></a></section>
 <footer className="rp-footer"><div><b>RUPTIX<span>.</span></b><p>Tecnologia para transformar operações.</p></div><div><strong>RUPCONTROL</strong><a href={SIGNUP_URL}>Teste grátis por 14 dias</a><a href={APP_URL+"/login"}>Acessar sistema</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><small>© 2026 Ruptix. Todos os direitos reservados.</small></footer>
 </main>}