"use client";
import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";
import Sidebar from "./Sidebar";
import BillingPanel from "./BillingPanel";
import ConsentScreen from "../../_components/ConsentScreen";
import {useWorkspace} from "../../../lib/use-workspace";
const roleLabel={owner:"Proprietário",manager:"Gerente",reception:"Recepção",attendant:"Atendente",barber:"Barbeiro"};
export default function ModuleShell({children,title,eyebrow="Gestão",action}){
 const workspace=useWorkspace(),pathname=usePathname(),[notice,setNotice]=useState(false),[sidebarCollapsed,setSidebarCollapsed]=useState(false);
 useEffect(()=>{if(!workspace.loading&&workspace.tenant?.id){const today=new Date().toISOString().slice(0,10),key="billing_notice_"+workspace.tenant.id;setNotice(localStorage.getItem(key)!==today)}},[workspace.loading,workspace.tenant?.id]);
 useEffect(()=>{try{setSidebarCollapsed(localStorage.getItem("barberflow_sidebar_collapsed")==="1")}catch{}},[]);
 function toggleSidebar(){setSidebarCollapsed(v=>{const next=!v;try{localStorage.setItem("barberflow_sidebar_collapsed",next?"1":"0")}catch{}return next})}
 if(workspace.loading||workspace.onboardingRequired)return <main className="center-state bt-loading" aria-busy="true"><span className="bt-loader-mark" aria-hidden="true"/><span>{workspace.onboardingRequired?"Abrindo configuração inicial...":"Carregando BarberTix..."}</span></main>;
 if(workspace.consentRequired)return <ConsentScreen onAccepted={workspace.reload}/>;
 if(workspace.error)return <main className="center-state"><div className="box"><h2>Acesso ainda não liberado</h2><p>{workspace.error}</p><a href="/login">Voltar ao login</a></div></main>;
 // Trial over (or blocked for non-payment): the owner only sees plan choice and payment.
 if(workspace.billingLock)return <main className={"dash dashboard-shell "+(sidebarCollapsed?"sidebar-mini":"")}><Sidebar workspace={workspace} collapsed={sidebarCollapsed} onToggle={toggleSidebar}/><section className="content"><header className="topbar"><div><p className="eyebrow">Assinatura</p><h1>{workspace.billingLock==="trial_ended"?"Escolha seu plano":"Regularize sua mensalidade"}</h1><p className="topbar-copy">{workspace.tenant?.name} · {roleLabel[workspace.membership?.role]||workspace.membership?.role}</p></div></header><BillingPanel workspace={workspace} locked={workspace.billingLock}/></section></main>;
 const starter=String(workspace.tenant?.plans?.name||"").toLowerCase()==="starter",starterAllowed=pathname==="/dashboard"||pathname.startsWith("/dashboard/clientes")||pathname.startsWith("/dashboard/barbeiros")||pathname.startsWith("/dashboard/servicos")||pathname.startsWith("/dashboard/financeiro")||pathname.startsWith("/dashboard/estoque")||pathname.startsWith("/dashboard/comandas")||pathname.startsWith("/dashboard/vendas")||pathname.startsWith("/dashboard/caixa")||pathname.startsWith("/dashboard/relatorios")||pathname.startsWith("/dashboard/comissoes")||pathname.startsWith("/dashboard/mensalidade");
 if(starter&&!starterAllowed)return <main className={"dash dashboard-shell "+(sidebarCollapsed?"sidebar-mini":"")}><Sidebar workspace={workspace} collapsed={sidebarCollapsed} onToggle={toggleSidebar}/><section className="content"><header className="topbar"><div><p className="eyebrow">PLANO STARTER</p><h1>Recurso não incluído</h1><p className="topbar-copy">O Starter inclui a gestão interna, mas não inclui agenda pública nem robô do WhatsApp.</p></div></header><section className="box"><h2>Disponível nos planos Pro e Pro + Filiais</h2><p>Agenda, site público de agendamento e WhatsApp automatizado ficam disponíveis a partir do plano Pro.</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:16}}><a className="primary" href="/dashboard">Ir para vendas</a><a className="secondary-action" href="/dashboard/mensalidade">Ver assinatura</a></div></section></section></main>;
 const overdue=workspace.tenant?.status==="overdue",dueDate=workspace.tenant?.billing_due_date?new Date(workspace.tenant.billing_due_date+"T12:00:00"):null,due=dueDate?.toLocaleDateString("pt-BR"),graceDays=Number(workspace.tenant?.grace_days||0),blockDate=dueDate?new Date(dueDate.getTime()+graceDays*86400000):null,block=blockDate?.toLocaleDateString("pt-BR"),daysToDue=dueDate?Math.ceil((dueDate-new Date())/86400000):null,upcoming=workspace.tenant?.status==="active"&&daysToDue!==null&&daysToDue>=0&&daysToDue<=3,trialEnd=workspace.tenant?.trial_ends_at?new Date(workspace.tenant.trial_ends_at+"T12:00:00"):null,trialDays=trialEnd?Math.max(0,Math.ceil((trialEnd-new Date())/86400000)):null;
 function closeNotice(){const today=new Date().toISOString().slice(0,10),key="billing_notice_"+workspace.tenant.id;localStorage.setItem(key,today);setNotice(false)}
 return <main className={"dash dashboard-shell "+(sidebarCollapsed?"sidebar-mini":"")}><Sidebar workspace={workspace} collapsed={sidebarCollapsed} onToggle={toggleSidebar}/><section className="content">{workspace.tenant?.status==="trial"&&trialDays!==null&&notice&&<div className="form-alert"><strong>Período de teste ativo.</strong> {trialDays===0?"Seu trial termina hoje.":`Restam ${trialDays} ${trialDays===1?"dia":"dias"}.`} <a href="/dashboard/mensalidade">Ver plano</a> <button type="button" onClick={closeNotice}>Fechar</button></div>}{upcoming&&notice&&<div className="form-alert"><strong>Mensalidade próxima do vencimento.</strong> {due?`Vence em ${due}. `:""}Regularize o pagamento para manter o BarberTix em dia. <button type="button" onClick={closeNotice}>Fechar</button></div>}{overdue&&notice&&<div className="form-alert error"><strong>Mensalidade em atraso.</strong> {due?`Vencimento: ${due}. `:""}{block?`O sistema será bloqueado após o período de ${graceDays} ${graceDays===1?"dia":"dias"}, em ${block}. `:""}Entre em contato com o BarberTix para regularizar o pagamento. <button type="button" onClick={closeNotice}>Fechar</button></div>}<header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="topbar-copy">{workspace.tenant?.name} · {roleLabel[workspace.membership?.role]||workspace.membership?.role}</p></div>{typeof action==="function"?action(workspace):action}</header>{typeof children==="function"?children(workspace):children}</section></main>;
}
