"use client";
import {useEffect,useState} from "react";
import Sidebar from "./Sidebar";
import {useWorkspace} from "../../../lib/use-workspace";
const PIX_KEY="sonorag4@hotmail.com";
const clean=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Za-z0-9 ]/g,"").toUpperCase().slice(0,25);
const field=(id,v)=>id+String(v.length).padStart(2,"0")+v;
function crc16(str){let crc=0xffff;for(let i=0;i<str.length;i++){crc^=str.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=(crc&0x8000)?(crc<<1)^0x1021:crc<<1;crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,"0")}
function pixPayload(name,cents){const desc=("BARBER FLOW "+clean(name)).slice(0,72),merchant=field("00","BR.GOV.BCB.PIX")+field("01",PIX_KEY)+field("02",desc),amount=(Number(cents||0)/100).toFixed(2),base=field("00","01")+field("26",merchant)+field("52","0000")+field("53","986")+field("54",amount)+field("58","BR")+field("59","BARBER FLOW")+field("60","SAO PAULO")+field("62",field("05","***"))+"6304";return base+crc16(base)}
export default function ModuleShell({children,title,eyebrow="Gestão",action}){
 const workspace=useWorkspace(),[pay,setPay]=useState(false),[copied,setCopied]=useState(false),[notice,setNotice]=useState(false);
 useEffect(()=>{if(!workspace.loading&&workspace.tenant?.id){const today=new Date().toISOString().slice(0,10),key="billing_notice_"+workspace.tenant.id;setNotice(localStorage.getItem(key)!==today)}},[workspace.loading,workspace.tenant?.id]);
 if(workspace.loading)return <main className="center-state">Carregando Barber Flow...</main>;
 if(workspace.error)return <main className="center-state"><div className="box"><h2>Acesso ainda não liberado</h2><p>{workspace.error}</p><a href="/login">Voltar ao login</a></div></main>;
 const overdue=workspace.tenant?.status==="overdue",dueDate=workspace.tenant?.billing_due_date?new Date(workspace.tenant.billing_due_date+"T12:00:00"):null,due=dueDate?.toLocaleDateString("pt-BR"),blockDate=dueDate?new Date(dueDate.getTime()+7*86400000):null,block=blockDate?.toLocaleDateString("pt-BR"),daysToDue=dueDate?Math.ceil((dueDate-new Date())/86400000):null,upcoming=workspace.tenant?.status==="active"&&daysToDue!==null&&daysToDue>=0&&daysToDue<=3,amount=workspace.tenant?.plans?.monthly_cents||0,pix=amount?pixPayload(workspace.tenant?.name,amount):"";
 function closeNotice(){const today=new Date().toISOString().slice(0,10),key="billing_notice_"+workspace.tenant.id;localStorage.setItem(key,today);setNotice(false)}
 async function copy(){await navigator.clipboard.writeText(pix);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <main className="dash"><Sidebar workspace={workspace}/><section className="content">{upcoming&&notice&&<div className="form-alert"><strong>Mensalidade próxima do vencimento.</strong> {due?`Vence em ${due}. `:""}Regularize o pagamento para manter o Barber Flow em dia. <button type="button" onClick={closeNotice}>Fechar</button></div>}{overdue&&notice&&<div className="form-alert error"><strong>Mensalidade em atraso.</strong> {due?`Vencimento: ${due}. `:""}{block?`O sistema será bloqueado após o período de 7 dias, em ${block}. `:""}Entre em contato com o Barber Flow para regularizar o pagamento. <button type="button" onClick={closeNotice}>Fechar</button></div>}<header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="topbar-copy">{workspace.tenant?.name} · {workspace.membership?.role}</p></div>{action}</header>{typeof children==="function"?children(workspace):children}{workspace.membership?.role==="owner"&&amount>0&&<section id="mensalidade" className="billing-pay-box"><div><small>Mensalidade · {workspace.tenant?.plans?.name||"Plano"} · {(amount/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</small></div><button className="billing-pay-link" type="button" onClick={()=>setPay(!pay)}>{pay?"Fechar":"Pagar agora"}</button>{pay&&<div className="billing-pix"><strong>PIX Copia e Cola</strong><p>Chave: {PIX_KEY}</p><textarea readOnly value={pix}/><button type="button" className="secondary-action" onClick={copy}>{copied?"PIX copiado":"Copiar PIX"}</button><small>Descrição do PIX: BARBER FLOW {workspace.tenant?.name}</small></div>}</section>}</section></main>;
}