"use client";
import {notify} from "../../../lib/notify";
import {useCallback,useEffect,useState,useRef} from 'react';
import {Plus,X} from 'lucide-react';
import {supabase} from '../../../lib/supabase';
import ModuleShell from '../_components/ModuleShell';
const money=n=>(Number(n||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const methods={cash:'Dinheiro',pix:'Pix',credit:'Cartão de crédito',debit:'Cartão de débito',transfer:'Transferência'};
const statusName={open:'Em aberto',paid:'Liquidado',cancelled:'Cancelado'};
function Finance({workspace}){
 const t=workspace.tenant.id,m=workspace.membership,allowed=m.role==='owner'||(['manager','reception'].includes(m.role)&&m.permissions?.includes('finance'));
 const [units,setUnits]=useState([]),[unit,setUnit]=useState(''),[from,setFrom]=useState(()=>today().slice(0,7)+'-01'),[to,setTo]=useState(today),[items,setItems]=useState([]),[summary,setSummary]=useState(null),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[modal,setModal]=useState(null);
 const sequence=useRef(0);
 const load=useCallback(async()=>{const version=++sequence.current;if(!allowed){setLoading(false);return}setLoading(true);setError('');try{if(!from||!to||from>to)throw new Error('Confira as datas do período.');const end=new Date(to+'T00:00:00');end.setDate(end.getDate()+1);let query=supabase.from('financial_entries').select('*').eq('tenant_id',t).gte('due_date',from).lte('due_date',to).order('due_date').limit(200);if(unit)query=query.eq('unit_id',unit);if(status!=='all')query=query.eq('status',status);
 const results=await Promise.all([supabase.from('units').select('id,name,active').eq('tenant_id',t),query,supabase.rpc('finance_summary',{t,u:unit||null,st:new Date(from+'T00:00:00').toISOString(),en:end.toISOString()})]);if(version!==sequence.current)return;const fail=results.find(r=>r.error)?.error;if(fail)throw fail;setUnits(results[0].data||[]);setItems(results[1].data||[]);setSummary(results[2].data)}catch(e){if(version===sequence.current){setError(e.message);setSummary(null)}}finally{if(version===sequence.current)setLoading(false)}},[t,unit,from,to,status,allowed]);
 useEffect(()=>{load()},[load]);
 function open(type,item=null){setError('');setMessage('');setModal({type,item,key:crypto.randomUUID()})}
 async function submit(e){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{let r;if(modal.type==='new')r=await supabase.rpc('finance_create',{t,r:modal.key,p:{unit_id:f.get('unit_id'),kind:f.get('kind'),description:f.get('description'),category:f.get('category'),counterparty:f.get('counterparty'),amount_cents:Math.round(Number(f.get('amount'))*100),due_date:f.get('due_date')}});else if(modal.type==='settle')r=await supabase.rpc('finance_settle',{t,i:modal.item.id,m:f.get('method')});else r=await supabase.rpc('finance_cancel',{t,i:modal.item.id,reason:f.get('reason')});if(r.error)throw r.error;setModal(null);setMessage('Operação registrada no histórico financeiro.');notify(modal.type==='new'?'Lançamento financeiro criado com sucesso.':modal.type==='settle'?'Pagamento atualizado com sucesso.':'Lançamento cancelado e histórico atualizado.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function exportCsv(){const rows=[['Vencimento','Tipo','Descrição','Unidade','Valor','Status','Pagamento'],...items.map(x=>[x.due_date,x.kind==='income'?'Receita':'Despesa',x.description,units.find(u=>u.id===x.unit_id)?.name||'',(x.amount_cents/100).toFixed(2),statusName[x.status],methods[x.method]||''])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='financeiro.csv';a.click();URL.revokeObjectURL(url)}
 if(!allowed)return <section className="box"><h2>Acesso restrito</h2><p>O proprietário precisa conceder a permissão de financeiro.</p></section>;
 return <><section className="box inventory-header"><div><h2>Controle financeiro</h2><p>Receitas, despesas e contas. Vendas entram automaticamente no resumo.</p></div><button className="primary" disabled={!units.some(u=>u.active)} onClick={()=>open('new')}><Plus size={18}/>Novo lançamento</button></section>{error&&!modal&&<p role="alert" className="form-alert error">{error}</p>}{message&&<p role="status" className="form-alert success">{message}</p>}
 <section className="box"><div className="inventory-filters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Todas as unidades</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Lista de contas<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option>{Object.entries(statusName).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><p>Resumo pelo dia do recebimento/pagamento, no fuso do dispositivo. Contas abaixo pelo vencimento. Valores a pagar/receber incluem todas as datas.</p></section>
 {loading?<p className="empty">Carregando financeiro...</p>:summary&&<div className="report-cards finance-cards">{[['Vendas recebidas',summary.sales_received],['Outras receitas recebidas',summary.other_income],['Despesas pagas',summary.expenses_paid],['Saldo do período',summary.net],['Total a receber',summary.receivable],['Total a pagar',summary.payable]].map(([label,value])=><div className="metric-card" key={label}><small>{label}</small><strong>{money(value)}</strong></div>)}</div>}
 <section className="box"><div className="inventory-header"><div><h2>Contas e lançamentos manuais</h2><p>Até 200 registros do período. Consulte vendas e seus saldos em Vendas e Clientes.</p></div><button onClick={exportCsv} disabled={loading||!items.length}>Exportar CSV</button></div><div className="inventory-grid">{items.map(x=><article className="inventory-card" key={x.id}><div className="inventory-card-title"><h3>{x.description}</h3><span className="pill">{statusName[x.status]}</span></div><p>{x.kind==='income'?'Receita':'Despesa'} · {x.category||'Sem categoria'} · {units.find(u=>u.id===x.unit_id)?.name}</p><strong>{money(x.amount_cents)}</strong><p>Vence em {new Date(x.due_date+'T12:00:00').toLocaleDateString('pt-BR')}{x.counterparty?' · '+x.counterparty:''}</p>{x.paid_at&&<p>Baixa: {new Date(x.paid_at).toLocaleString('pt-BR')} · {methods[x.method]}</p>}{x.cancellation_reason&&<p>Motivo: {x.cancellation_reason}</p>}<div className="inventory-actions">{x.status==='open'&&<button className="primary" onClick={()=>open('settle',x)}>{x.kind==='income'?'Registrar recebimento':'Registrar pagamento'}</button>}{x.status!=='cancelled'&&<button onClick={()=>open('cancel',x)}>Cancelar lançamento</button>}</div></article>)}</div>{!loading&&!items.length&&<p className="empty">Nenhum lançamento encontrado neste período.</p>}</section>
 {modal&&<div className="checkout-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="finance-title" className="checkout-modal inventory-modal"><button className="checkout-close" aria-label="Fechar" disabled={busy} onClick={()=>setModal(null)}><X/></button><h2 id="finance-title">{modal.type==='new'?'Novo lançamento':modal.type==='settle'?'Confirmar baixa':'Cancelar lançamento'}</h2>{modal.item&&<p>{modal.item.description} · {money(modal.item.amount_cents)}</p>}{error&&<p role="alert" className="form-alert error">{error}</p>}<form onSubmit={submit}><fieldset className="inventory-fieldset" disabled={busy}><div className="form-grid">{modal.type==='new'?<><label>Tipo<select name="kind"><option value="expense">Despesa / conta a pagar</option><option value="income">Receita / conta a receber</option></select></label><label>Unidade<select name="unit_id" defaultValue={unit||units.find(u=>u.active)?.id} required>{units.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Descrição<input name="description" minLength={2} maxLength={200} required/></label><label>Categoria<input name="category" maxLength={100} placeholder="Ex.: aluguel, energia"/></label><label>Fornecedor / pagador<input name="counterparty" maxLength={150}/></label><label>Valor (R$)<input name="amount" type="number" min="0.01" max="21474836" step="0.01" required/></label><label>Vencimento<input name="due_date" type="date" defaultValue={today()} required/></label><p>O lançamento inicia em aberto. Registre a baixa após conferir o pagamento. Não repita aqui uma venda já cadastrada.</p></>:modal.type==='settle'?<><label>Forma de pagamento<select name="method">{Object.entries(methods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="inventory-check"><input type="checkbox" required/>Conferi o pagamento/recebimento. Esta ação apenas registra a baixa e não transfere dinheiro.</label></>:<><label>Motivo<input name="reason" minLength={3} maxLength={500} required/></label><p>O registro será preservado e deixará de compor os totais. Esta ação não faz estorno bancário.</p></>}</div><button className="primary form-submit" disabled={busy}>{busy?'Salvando...':'Confirmar'}</button></fieldset></form></section></div>}</>;
}
export default function FinancePage(){return <ModuleShell title="Financeiro" eyebrow="Controle financeiro">{workspace=><Finance workspace={workspace}/>}</ModuleShell>}
